// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    string `json:"expiresAt"`
	UserID       string `json:"userId"`
	Address      string `json:"address"`
	ChainID      string `json:"chainId"`
}

type LinkWalletInput struct {
	AccountID string  `json:"accountId"`
	Address   string  `json:"address"`
	ChainID   string  `json:"chainId"`
	IsPrimary bool    `json:"isPrimary"`
	Type      *string `json:"type,omitempty"`
	Connector *string `json:"connector,omitempty"`
	Label     *string `json:"label,omitempty"`
}

type Mutation struct {
}

type Nonce struct {
	Nonce     string `json:"nonce"`
	ExpiresAt string `json:"expiresAt"`
}

type Profile struct {
	UserID      string  `json:"userId"`
	Username    *string `json:"username,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	BannerURL   *string `json:"bannerUrl,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	Timezone    *string `json:"timezone,omitempty"`
	SocialsJSON *string `json:"socialsJson,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

type Query struct {
}

type RefreshResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    string `json:"expiresAt"`
	UserID       string `json:"userId"`
}

type UpdateProfileInput struct {
	Username    *string `json:"username,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	BannerURL   *string `json:"bannerUrl,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	Locale      *string `json:"locale,omitempty"`
	Timezone    *string `json:"timezone,omitempty"`
	SocialsJSON *string `json:"socialsJson,omitempty"`
}

type User struct {
	ID        string   `json:"id"`
	Status    string   `json:"status"`
	CreatedAt string   `json:"createdAt"`
	Profile   *Profile `json:"profile,omitempty"`
}

type WalletLink struct {
	ID         string  `json:"id"`
	UserID     string  `json:"userId"`
	AccountID  string  `json:"accountId"`
	Address    string  `json:"address"`
	ChainID    string  `json:"chainId"`
	IsPrimary  bool    `json:"isPrimary"`
	VerifiedAt *string `json:"verifiedAt,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}
