run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable:
      - shadow
      - fieldalignment
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/quangdang46/NFT-Marketplace
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  revive:
    confidence: 0.8

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - unconvert
    - dupl
    - prealloc
    - noctx
    - funlen
    - whitespace
    - revive # Replace deprecated golint
  disable:
    - varcheck # Deprecated (merged into unused)
    - deadcode # Deprecated (merged into unused)
    - structcheck # Deprecated (merged into unused)
    - golint # Deprecated (replaced by revive)
    - exportloopref # Deprecated in Go 1.22+

issues:
  # Use new exclude options instead of deprecated skip-dirs/skip-files
  exclude-dirs:
    - vendor
    - proto
    - tools
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
    - ".*generated.*\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    - path: cmd/
      linters:
        - gocyclo
        - funlen
    - text: 'Use of weak random number generator'
      linters:
        - gosec
    - text: 'Subprocess launched with variable'
      linters:
        - gosec
    - text: 'G404:'
      linters:
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
