// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc1
// source: chain-registry.proto

package chainregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== Enums =====
type RpcAuthType int32

const (
	RpcAuthType_RPC_AUTH_NONE   RpcAuthType = 0
	RpcAuthType_RPC_AUTH_KEY    RpcAuthType = 1
	RpcAuthType_RPC_AUTH_BASIC  RpcAuthType = 2
	RpcAuthType_RPC_AUTH_BEARER RpcAuthType = 3
)

// Enum value maps for RpcAuthType.
var (
	RpcAuthType_name = map[int32]string{
		0: "RPC_AUTH_NONE",
		1: "RPC_AUTH_KEY",
		2: "RPC_AUTH_BASIC",
		3: "RPC_AUTH_BEARER",
	}
	RpcAuthType_value = map[string]int32{
		"RPC_AUTH_NONE":   0,
		"RPC_AUTH_KEY":    1,
		"RPC_AUTH_BASIC":  2,
		"RPC_AUTH_BEARER": 3,
	}
)

func (x RpcAuthType) Enum() *RpcAuthType {
	p := new(RpcAuthType)
	*p = x
	return p
}

func (x RpcAuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcAuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_registry_proto_enumTypes[0].Descriptor()
}

func (RpcAuthType) Type() protoreflect.EnumType {
	return &file_chain_registry_proto_enumTypes[0]
}

func (x RpcAuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcAuthType.Descriptor instead.
func (RpcAuthType) EnumDescriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{0}
}

type ContractStandard int32

const (
	ContractStandard_STD_CUSTOM  ContractStandard = 0
	ContractStandard_STD_ERC721  ContractStandard = 1
	ContractStandard_STD_ERC1155 ContractStandard = 2
	ContractStandard_STD_PROXY   ContractStandard = 3
	ContractStandard_STD_DIAMOND ContractStandard = 4
)

// Enum value maps for ContractStandard.
var (
	ContractStandard_name = map[int32]string{
		0: "STD_CUSTOM",
		1: "STD_ERC721",
		2: "STD_ERC1155",
		3: "STD_PROXY",
		4: "STD_DIAMOND",
	}
	ContractStandard_value = map[string]int32{
		"STD_CUSTOM":  0,
		"STD_ERC721":  1,
		"STD_ERC1155": 2,
		"STD_PROXY":   3,
		"STD_DIAMOND": 4,
	}
)

func (x ContractStandard) Enum() *ContractStandard {
	p := new(ContractStandard)
	*p = x
	return p
}

func (x ContractStandard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractStandard) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_registry_proto_enumTypes[1].Descriptor()
}

func (ContractStandard) Type() protoreflect.EnumType {
	return &file_chain_registry_proto_enumTypes[1]
}

func (x ContractStandard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractStandard.Descriptor instead.
func (ContractStandard) EnumDescriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{1}
}

// ===== Models =====
type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // 0x...
	StartBlock    int32                  `protobuf:"varint,3,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	VerifiedAt    string                 `protobuf:"bytes,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`                // RFC3339
	Standard      ContractStandard       `protobuf:"varint,5,opt,name=standard,proto3,enum=chainregistry.ContractStandard" json:"standard,omitempty"` // <— thêm
	ImplAddress   string                 `protobuf:"bytes,6,opt,name=impl_address,json=implAddress,proto3" json:"impl_address,omitempty"`             // <— thêm (proxy)
	AbiSha256     string                 `protobuf:"bytes,7,opt,name=abi_sha256,json=abiSha256,proto3" json:"abi_sha256,omitempty"`                   // <— thêm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_chain_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Contract) GetStartBlock() int32 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Contract) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *Contract) GetStandard() ContractStandard {
	if x != nil {
		return x.Standard
	}
	return ContractStandard_STD_CUSTOM
}

func (x *Contract) GetImplAddress() string {
	if x != nil {
		return x.ImplAddress
	}
	return ""
}

func (x *Contract) GetAbiSha256() string {
	if x != nil {
		return x.AbiSha256
	}
	return ""
}

type GasPolicy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxFeeGwei              float64                `protobuf:"fixed64,1,opt,name=max_fee_gwei,json=maxFeeGwei,proto3" json:"max_fee_gwei,omitempty"`
	PriorityFeeGwei         float64                `protobuf:"fixed64,2,opt,name=priority_fee_gwei,json=priorityFeeGwei,proto3" json:"priority_fee_gwei,omitempty"`
	Multiplier              float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	LastObservedBaseFeeGwei float64                `protobuf:"fixed64,4,opt,name=last_observed_base_fee_gwei,json=lastObservedBaseFeeGwei,proto3" json:"last_observed_base_fee_gwei,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GasPolicy) Reset() {
	*x = GasPolicy{}
	mi := &file_chain_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasPolicy) ProtoMessage() {}

func (x *GasPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasPolicy.ProtoReflect.Descriptor instead.
func (*GasPolicy) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{1}
}

func (x *GasPolicy) GetMaxFeeGwei() float64 {
	if x != nil {
		return x.MaxFeeGwei
	}
	return 0
}

func (x *GasPolicy) GetPriorityFeeGwei() float64 {
	if x != nil {
		return x.PriorityFeeGwei
	}
	return 0
}

func (x *GasPolicy) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *GasPolicy) GetLastObservedBaseFeeGwei() float64 {
	if x != nil {
		return x.LastObservedBaseFeeGwei
	}
	return 0
}

func (x *GasPolicy) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RpcEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	AuthType      RpcAuthType            `protobuf:"varint,4,opt,name=auth_type,json=authType,proto3,enum=chainregistry.RpcAuthType" json:"auth_type,omitempty"` // enum
	RateLimit     int32                  `protobuf:"varint,5,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcEndpoint) Reset() {
	*x = RpcEndpoint{}
	mi := &file_chain_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEndpoint) ProtoMessage() {}

func (x *RpcEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEndpoint.ProtoReflect.Descriptor instead.
func (*RpcEndpoint) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RpcEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RpcEndpoint) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RpcEndpoint) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RpcEndpoint) GetAuthType() RpcAuthType {
	if x != nil {
		return x.AuthType
	}
	return RpcAuthType_RPC_AUTH_NONE
}

func (x *RpcEndpoint) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *RpcEndpoint) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ChainParams struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequiredConfirmations uint32                 `protobuf:"varint,1,opt,name=required_confirmations,json=requiredConfirmations,proto3" json:"required_confirmations,omitempty"`
	ReorgDepth            uint32                 `protobuf:"varint,2,opt,name=reorg_depth,json=reorgDepth,proto3" json:"reorg_depth,omitempty"`      // <— thêm
	BlockTimeMs           uint32                 `protobuf:"varint,3,opt,name=block_time_ms,json=blockTimeMs,proto3" json:"block_time_ms,omitempty"` // <— thêm
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChainParams) Reset() {
	*x = ChainParams{}
	mi := &file_chain_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainParams) ProtoMessage() {}

func (x *ChainParams) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainParams.ProtoReflect.Descriptor instead.
func (*ChainParams) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ChainParams) GetRequiredConfirmations() uint32 {
	if x != nil {
		return x.RequiredConfirmations
	}
	return 0
}

func (x *ChainParams) GetReorgDepth() uint32 {
	if x != nil {
		return x.ReorgDepth
	}
	return 0
}

func (x *ChainParams) GetBlockTimeMs() uint32 {
	if x != nil {
		return x.BlockTimeMs
	}
	return 0
}

// ===== Requests / Responses =====
type GetContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractsRequest) Reset() {
	*x = GetContractsRequest{}
	mi := &file_chain_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractsRequest) ProtoMessage() {}

func (x *GetContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractsRequest.ProtoReflect.Descriptor instead.
func (*GetContractsRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetContractsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type GetContractsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainNumeric    uint64                 `protobuf:"varint,2,opt,name=chain_numeric,json=chainNumeric,proto3" json:"chain_numeric,omitempty"`
	Contracts       []*Contract            `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Params          *ChainParams           `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // <— gom vào đây
	RegistryVersion string                 `protobuf:"bytes,5,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	NativeSymbol    string                 `protobuf:"bytes,6,opt,name=native_symbol,json=nativeSymbol,proto3" json:"native_symbol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetContractsResponse) Reset() {
	*x = GetContractsResponse{}
	mi := &file_chain_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractsResponse) ProtoMessage() {}

func (x *GetContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractsResponse.ProtoReflect.Descriptor instead.
func (*GetContractsResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetContractsResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetContractsResponse) GetChainNumeric() uint64 {
	if x != nil {
		return x.ChainNumeric
	}
	return 0
}

func (x *GetContractsResponse) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *GetContractsResponse) GetParams() *ChainParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetContractsResponse) GetRegistryVersion() string {
	if x != nil {
		return x.RegistryVersion
	}
	return ""
}

func (x *GetContractsResponse) GetNativeSymbol() string {
	if x != nil {
		return x.NativeSymbol
	}
	return ""
}

type GetGasPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGasPolicyRequest) Reset() {
	*x = GetGasPolicyRequest{}
	mi := &file_chain_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGasPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGasPolicyRequest) ProtoMessage() {}

func (x *GetGasPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGasPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetGasPolicyRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetGasPolicyRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type GetGasPolicyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Policy          *GasPolicy             `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	RegistryVersion string                 `protobuf:"bytes,3,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGasPolicyResponse) Reset() {
	*x = GetGasPolicyResponse{}
	mi := &file_chain_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGasPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGasPolicyResponse) ProtoMessage() {}

func (x *GetGasPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGasPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetGasPolicyResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{7}
}

func (x *GetGasPolicyResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetGasPolicyResponse) GetPolicy() *GasPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetGasPolicyResponse) GetRegistryVersion() string {
	if x != nil {
		return x.RegistryVersion
	}
	return ""
}

type GetRpcEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRpcEndpointsRequest) Reset() {
	*x = GetRpcEndpointsRequest{}
	mi := &file_chain_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRpcEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRpcEndpointsRequest) ProtoMessage() {}

func (x *GetRpcEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRpcEndpointsRequest.ProtoReflect.Descriptor instead.
func (*GetRpcEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetRpcEndpointsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type GetRpcEndpointsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Endpoints       []*RpcEndpoint         `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	RegistryVersion string                 `protobuf:"bytes,3,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRpcEndpointsResponse) Reset() {
	*x = GetRpcEndpointsResponse{}
	mi := &file_chain_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRpcEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRpcEndpointsResponse) ProtoMessage() {}

func (x *GetRpcEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRpcEndpointsResponse.ProtoReflect.Descriptor instead.
func (*GetRpcEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetRpcEndpointsResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetRpcEndpointsResponse) GetEndpoints() []*RpcEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *GetRpcEndpointsResponse) GetRegistryVersion() string {
	if x != nil {
		return x.RegistryVersion
	}
	return ""
}

type GetContractMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractMetaRequest) Reset() {
	*x = GetContractMetaRequest{}
	mi := &file_chain_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractMetaRequest) ProtoMessage() {}

func (x *GetContractMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractMetaRequest.ProtoReflect.Descriptor instead.
func (*GetContractMetaRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetContractMetaRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetContractMetaRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetContractMetaResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Contract        *Contract              `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	RegistryVersion string                 `protobuf:"bytes,3,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetContractMetaResponse) Reset() {
	*x = GetContractMetaResponse{}
	mi := &file_chain_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractMetaResponse) ProtoMessage() {}

func (x *GetContractMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractMetaResponse.ProtoReflect.Descriptor instead.
func (*GetContractMetaResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GetContractMetaResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetContractMetaResponse) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetContractMetaResponse) GetRegistryVersion() string {
	if x != nil {
		return x.RegistryVersion
	}
	return ""
}

type GetAbiBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbiSha256     string                 `protobuf:"bytes,1,opt,name=abi_sha256,json=abiSha256,proto3" json:"abi_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbiBlobRequest) Reset() {
	*x = GetAbiBlobRequest{}
	mi := &file_chain_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbiBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbiBlobRequest) ProtoMessage() {}

func (x *GetAbiBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbiBlobRequest.ProtoReflect.Descriptor instead.
func (*GetAbiBlobRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{12}
}

func (x *GetAbiBlobRequest) GetAbiSha256() string {
	if x != nil {
		return x.AbiSha256
	}
	return ""
}

type GetAbiBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbiJson       string                 `protobuf:"bytes,1,opt,name=abi_json,json=abiJson,proto3" json:"abi_json,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbiBlobResponse) Reset() {
	*x = GetAbiBlobResponse{}
	mi := &file_chain_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbiBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbiBlobResponse) ProtoMessage() {}

func (x *GetAbiBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbiBlobResponse.ProtoReflect.Descriptor instead.
func (*GetAbiBlobResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{13}
}

func (x *GetAbiBlobResponse) GetAbiJson() string {
	if x != nil {
		return x.AbiJson
	}
	return ""
}

func (x *GetAbiBlobResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Friendly: get ABI directly by chain+address
type GetAbiByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbiByAddressRequest) Reset() {
	*x = GetAbiByAddressRequest{}
	mi := &file_chain_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbiByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbiByAddressRequest) ProtoMessage() {}

func (x *GetAbiByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbiByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAbiByAddressRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GetAbiByAddressRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetAbiByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResolveProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProxyRequest) Reset() {
	*x = ResolveProxyRequest{}
	mi := &file_chain_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProxyRequest) ProtoMessage() {}

func (x *ResolveProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProxyRequest.ProtoReflect.Descriptor instead.
func (*ResolveProxyRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveProxyRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ResolveProxyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResolveProxyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ProxyAddress    string                 `protobuf:"bytes,2,opt,name=proxy_address,json=proxyAddress,proto3" json:"proxy_address,omitempty"`
	ImplAddress     string                 `protobuf:"bytes,3,opt,name=impl_address,json=implAddress,proto3" json:"impl_address,omitempty"`
	AbiSha256       string                 `protobuf:"bytes,4,opt,name=abi_sha256,json=abiSha256,proto3" json:"abi_sha256,omitempty"`
	RegistryVersion string                 `protobuf:"bytes,5,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveProxyResponse) Reset() {
	*x = ResolveProxyResponse{}
	mi := &file_chain_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProxyResponse) ProtoMessage() {}

func (x *ResolveProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProxyResponse.ProtoReflect.Descriptor instead.
func (*ResolveProxyResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveProxyResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ResolveProxyResponse) GetProxyAddress() string {
	if x != nil {
		return x.ProxyAddress
	}
	return ""
}

func (x *ResolveProxyResponse) GetImplAddress() string {
	if x != nil {
		return x.ImplAddress
	}
	return ""
}

func (x *ResolveProxyResponse) GetAbiSha256() string {
	if x != nil {
		return x.AbiSha256
	}
	return ""
}

func (x *ResolveProxyResponse) GetRegistryVersion() string {
	if x != nil {
		return x.RegistryVersion
	}
	return ""
}

type BumpVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BumpVersionRequest) Reset() {
	*x = BumpVersionRequest{}
	mi := &file_chain_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpVersionRequest) ProtoMessage() {}

func (x *BumpVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpVersionRequest.ProtoReflect.Descriptor instead.
func (*BumpVersionRequest) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{17}
}

func (x *BumpVersionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *BumpVersionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BumpVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NewVersion    string                 `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BumpVersionResponse) Reset() {
	*x = BumpVersionResponse{}
	mi := &file_chain_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpVersionResponse) ProtoMessage() {}

func (x *BumpVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpVersionResponse.ProtoReflect.Descriptor instead.
func (*BumpVersionResponse) Descriptor() ([]byte, []int) {
	return file_chain_registry_proto_rawDescGZIP(), []int{18}
}

func (x *BumpVersionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BumpVersionResponse) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

var File_chain_registry_proto protoreflect.FileDescriptor

const file_chain_registry_proto_rawDesc = "" +
	"\n" +
	"\x14chain-registry.proto\x12\rchainregistry\"\xf9\x01\n" +
	"\bContract\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vstart_block\x18\x03 \x01(\x05R\n" +
	"startBlock\x12\x1f\n" +
	"\vverified_at\x18\x04 \x01(\tR\n" +
	"verifiedAt\x12;\n" +
	"\bstandard\x18\x05 \x01(\x0e2\x1f.chainregistry.ContractStandardR\bstandard\x12!\n" +
	"\fimpl_address\x18\x06 \x01(\tR\vimplAddress\x12\x1d\n" +
	"\n" +
	"abi_sha256\x18\a \x01(\tR\tabiSha256\"\xd6\x01\n" +
	"\tGasPolicy\x12 \n" +
	"\fmax_fee_gwei\x18\x01 \x01(\x01R\n" +
	"maxFeeGwei\x12*\n" +
	"\x11priority_fee_gwei\x18\x02 \x01(\x01R\x0fpriorityFeeGwei\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\x12<\n" +
	"\x1blast_observed_base_fee_gwei\x18\x04 \x01(\x01R\x17lastObservedBaseFeeGwei\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xc3\x01\n" +
	"\vRpcEndpoint\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x127\n" +
	"\tauth_type\x18\x04 \x01(\x0e2\x1a.chainregistry.RpcAuthTypeR\bauthType\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\x05R\trateLimit\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"\x89\x01\n" +
	"\vChainParams\x125\n" +
	"\x16required_confirmations\x18\x01 \x01(\rR\x15requiredConfirmations\x12\x1f\n" +
	"\vreorg_depth\x18\x02 \x01(\rR\n" +
	"reorgDepth\x12\"\n" +
	"\rblock_time_ms\x18\x03 \x01(\rR\vblockTimeMs\"0\n" +
	"\x13GetContractsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"\x91\x02\n" +
	"\x14GetContractsResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12#\n" +
	"\rchain_numeric\x18\x02 \x01(\x04R\fchainNumeric\x125\n" +
	"\tcontracts\x18\x03 \x03(\v2\x17.chainregistry.ContractR\tcontracts\x122\n" +
	"\x06params\x18\x04 \x01(\v2\x1a.chainregistry.ChainParamsR\x06params\x12)\n" +
	"\x10registry_version\x18\x05 \x01(\tR\x0fregistryVersion\x12#\n" +
	"\rnative_symbol\x18\x06 \x01(\tR\fnativeSymbol\"0\n" +
	"\x13GetGasPolicyRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"\x8e\x01\n" +
	"\x14GetGasPolicyResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x120\n" +
	"\x06policy\x18\x02 \x01(\v2\x18.chainregistry.GasPolicyR\x06policy\x12)\n" +
	"\x10registry_version\x18\x03 \x01(\tR\x0fregistryVersion\"3\n" +
	"\x16GetRpcEndpointsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"\x99\x01\n" +
	"\x17GetRpcEndpointsResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x128\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1a.chainregistry.RpcEndpointR\tendpoints\x12)\n" +
	"\x10registry_version\x18\x03 \x01(\tR\x0fregistryVersion\"M\n" +
	"\x16GetContractMetaRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x94\x01\n" +
	"\x17GetContractMetaResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x123\n" +
	"\bcontract\x18\x02 \x01(\v2\x17.chainregistry.ContractR\bcontract\x12)\n" +
	"\x10registry_version\x18\x03 \x01(\tR\x0fregistryVersion\"2\n" +
	"\x11GetAbiBlobRequest\x12\x1d\n" +
	"\n" +
	"abi_sha256\x18\x01 \x01(\tR\tabiSha256\"C\n" +
	"\x12GetAbiBlobResponse\x12\x19\n" +
	"\babi_json\x18\x01 \x01(\tR\aabiJson\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"M\n" +
	"\x16GetAbiByAddressRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"J\n" +
	"\x13ResolveProxyRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xc3\x01\n" +
	"\x14ResolveProxyResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12#\n" +
	"\rproxy_address\x18\x02 \x01(\tR\fproxyAddress\x12!\n" +
	"\fimpl_address\x18\x03 \x01(\tR\vimplAddress\x12\x1d\n" +
	"\n" +
	"abi_sha256\x18\x04 \x01(\tR\tabiSha256\x12)\n" +
	"\x10registry_version\x18\x05 \x01(\tR\x0fregistryVersion\"G\n" +
	"\x12BumpVersionRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"F\n" +
	"\x13BumpVersionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\tR\n" +
	"newVersion*[\n" +
	"\vRpcAuthType\x12\x11\n" +
	"\rRPC_AUTH_NONE\x10\x00\x12\x10\n" +
	"\fRPC_AUTH_KEY\x10\x01\x12\x12\n" +
	"\x0eRPC_AUTH_BASIC\x10\x02\x12\x13\n" +
	"\x0fRPC_AUTH_BEARER\x10\x03*c\n" +
	"\x10ContractStandard\x12\x0e\n" +
	"\n" +
	"STD_CUSTOM\x10\x00\x12\x0e\n" +
	"\n" +
	"STD_ERC721\x10\x01\x12\x0f\n" +
	"\vSTD_ERC1155\x10\x02\x12\r\n" +
	"\tSTD_PROXY\x10\x03\x12\x0f\n" +
	"\vSTD_DIAMOND\x10\x042\xeb\x05\n" +
	"\x14ChainRegistryService\x12W\n" +
	"\fGetContracts\x12\".chainregistry.GetContractsRequest\x1a#.chainregistry.GetContractsResponse\x12W\n" +
	"\fGetGasPolicy\x12\".chainregistry.GetGasPolicyRequest\x1a#.chainregistry.GetGasPolicyResponse\x12`\n" +
	"\x0fGetRpcEndpoints\x12%.chainregistry.GetRpcEndpointsRequest\x1a&.chainregistry.GetRpcEndpointsResponse\x12`\n" +
	"\x0fGetContractMeta\x12%.chainregistry.GetContractMetaRequest\x1a&.chainregistry.GetContractMetaResponse\x12Q\n" +
	"\n" +
	"GetAbiBlob\x12 .chainregistry.GetAbiBlobRequest\x1a!.chainregistry.GetAbiBlobResponse\x12[\n" +
	"\x0fGetAbiByAddress\x12%.chainregistry.GetAbiByAddressRequest\x1a!.chainregistry.GetAbiBlobResponse\x12W\n" +
	"\fResolveProxy\x12\".chainregistry.ResolveProxyRequest\x1a#.chainregistry.ResolveProxyResponse\x12T\n" +
	"\vBumpVersion\x12!.chainregistry.BumpVersionRequest\x1a\".chainregistry.BumpVersionResponseB*Z(shared/proto/chainregistry;chainregistryb\x06proto3"

var (
	file_chain_registry_proto_rawDescOnce sync.Once
	file_chain_registry_proto_rawDescData []byte
)

func file_chain_registry_proto_rawDescGZIP() []byte {
	file_chain_registry_proto_rawDescOnce.Do(func() {
		file_chain_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_registry_proto_rawDesc), len(file_chain_registry_proto_rawDesc)))
	})
	return file_chain_registry_proto_rawDescData
}

var file_chain_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chain_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chain_registry_proto_goTypes = []any{
	(RpcAuthType)(0),                // 0: chainregistry.RpcAuthType
	(ContractStandard)(0),           // 1: chainregistry.ContractStandard
	(*Contract)(nil),                // 2: chainregistry.Contract
	(*GasPolicy)(nil),               // 3: chainregistry.GasPolicy
	(*RpcEndpoint)(nil),             // 4: chainregistry.RpcEndpoint
	(*ChainParams)(nil),             // 5: chainregistry.ChainParams
	(*GetContractsRequest)(nil),     // 6: chainregistry.GetContractsRequest
	(*GetContractsResponse)(nil),    // 7: chainregistry.GetContractsResponse
	(*GetGasPolicyRequest)(nil),     // 8: chainregistry.GetGasPolicyRequest
	(*GetGasPolicyResponse)(nil),    // 9: chainregistry.GetGasPolicyResponse
	(*GetRpcEndpointsRequest)(nil),  // 10: chainregistry.GetRpcEndpointsRequest
	(*GetRpcEndpointsResponse)(nil), // 11: chainregistry.GetRpcEndpointsResponse
	(*GetContractMetaRequest)(nil),  // 12: chainregistry.GetContractMetaRequest
	(*GetContractMetaResponse)(nil), // 13: chainregistry.GetContractMetaResponse
	(*GetAbiBlobRequest)(nil),       // 14: chainregistry.GetAbiBlobRequest
	(*GetAbiBlobResponse)(nil),      // 15: chainregistry.GetAbiBlobResponse
	(*GetAbiByAddressRequest)(nil),  // 16: chainregistry.GetAbiByAddressRequest
	(*ResolveProxyRequest)(nil),     // 17: chainregistry.ResolveProxyRequest
	(*ResolveProxyResponse)(nil),    // 18: chainregistry.ResolveProxyResponse
	(*BumpVersionRequest)(nil),      // 19: chainregistry.BumpVersionRequest
	(*BumpVersionResponse)(nil),     // 20: chainregistry.BumpVersionResponse
}
var file_chain_registry_proto_depIdxs = []int32{
	1,  // 0: chainregistry.Contract.standard:type_name -> chainregistry.ContractStandard
	0,  // 1: chainregistry.RpcEndpoint.auth_type:type_name -> chainregistry.RpcAuthType
	2,  // 2: chainregistry.GetContractsResponse.contracts:type_name -> chainregistry.Contract
	5,  // 3: chainregistry.GetContractsResponse.params:type_name -> chainregistry.ChainParams
	3,  // 4: chainregistry.GetGasPolicyResponse.policy:type_name -> chainregistry.GasPolicy
	4,  // 5: chainregistry.GetRpcEndpointsResponse.endpoints:type_name -> chainregistry.RpcEndpoint
	2,  // 6: chainregistry.GetContractMetaResponse.contract:type_name -> chainregistry.Contract
	6,  // 7: chainregistry.ChainRegistryService.GetContracts:input_type -> chainregistry.GetContractsRequest
	8,  // 8: chainregistry.ChainRegistryService.GetGasPolicy:input_type -> chainregistry.GetGasPolicyRequest
	10, // 9: chainregistry.ChainRegistryService.GetRpcEndpoints:input_type -> chainregistry.GetRpcEndpointsRequest
	12, // 10: chainregistry.ChainRegistryService.GetContractMeta:input_type -> chainregistry.GetContractMetaRequest
	14, // 11: chainregistry.ChainRegistryService.GetAbiBlob:input_type -> chainregistry.GetAbiBlobRequest
	16, // 12: chainregistry.ChainRegistryService.GetAbiByAddress:input_type -> chainregistry.GetAbiByAddressRequest
	17, // 13: chainregistry.ChainRegistryService.ResolveProxy:input_type -> chainregistry.ResolveProxyRequest
	19, // 14: chainregistry.ChainRegistryService.BumpVersion:input_type -> chainregistry.BumpVersionRequest
	7,  // 15: chainregistry.ChainRegistryService.GetContracts:output_type -> chainregistry.GetContractsResponse
	9,  // 16: chainregistry.ChainRegistryService.GetGasPolicy:output_type -> chainregistry.GetGasPolicyResponse
	11, // 17: chainregistry.ChainRegistryService.GetRpcEndpoints:output_type -> chainregistry.GetRpcEndpointsResponse
	13, // 18: chainregistry.ChainRegistryService.GetContractMeta:output_type -> chainregistry.GetContractMetaResponse
	15, // 19: chainregistry.ChainRegistryService.GetAbiBlob:output_type -> chainregistry.GetAbiBlobResponse
	15, // 20: chainregistry.ChainRegistryService.GetAbiByAddress:output_type -> chainregistry.GetAbiBlobResponse
	18, // 21: chainregistry.ChainRegistryService.ResolveProxy:output_type -> chainregistry.ResolveProxyResponse
	20, // 22: chainregistry.ChainRegistryService.BumpVersion:output_type -> chainregistry.BumpVersionResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chain_registry_proto_init() }
func file_chain_registry_proto_init() {
	if File_chain_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_registry_proto_rawDesc), len(file_chain_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_registry_proto_goTypes,
		DependencyIndexes: file_chain_registry_proto_depIdxs,
		EnumInfos:         file_chain_registry_proto_enumTypes,
		MessageInfos:      file_chain_registry_proto_msgTypes,
	}.Build()
	File_chain_registry_proto = out.File
	file_chain_registry_proto_goTypes = nil
	file_chain_registry_proto_depIdxs = nil
}
