package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/graph/model"
	appcontext "github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/context"
	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/cookie"
	"github.com/zunokit/zuno-marketplace-api/shared/proto/pb"
)

// VerifySiwe is the resolver for the verifySiwe field.
func (r *mutationResolver) VerifySiwe(ctx context.Context, accountID string, message string, signature string) (*model.AuthResponse, error) {
	req := &pb.VerifySiweRequest{
		AccountId: accountID,
		Message:   message,
		Signature: signature,
	}

	res, err := r.AuthClient.VerifySiwe(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to verify SIWE: %w", err)
	}

	// Set refresh token as HTTP-only cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.SetRefreshTokenCookie(w, res.RefreshToken, cookie.MaxAge)
	}

	return &model.AuthResponse{
		AccessToken: res.AccessToken,
		ExpiresAt:   res.ExpiresAt,
		UserID:      res.UserId,
		Address:     res.Address,
		ChainID:     res.ChainId,
	}, nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, refreshToken *string, userAgent *string, ipAddress *string) (*model.RefreshResponse, error) {
	// Try to get refresh token from cookie if not provided
	var token string
	if refreshToken != nil && *refreshToken != "" {
		token = *refreshToken
	} else {
		if req, ok := appcontext.GetHTTPRequest(ctx); ok {
			if cookieToken, err := cookie.GetRefreshTokenFromCookie(req); err == nil {
				token = cookieToken
			}
		}
	}

	if token == "" {
		return nil, fmt.Errorf("refresh token required (either in parameter or cookie)")
	}

	req := &pb.RefreshSessionRequest{
		RefreshToken: token,
	}
	if userAgent != nil {
		req.UserAgent = *userAgent
	}
	if ipAddress != nil {
		req.IpAddress = *ipAddress
	}

	res, err := r.AuthClient.RefreshSession(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %w", err)
	}

	// Update refresh token cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.SetRefreshTokenCookie(w, res.RefreshToken, cookie.MaxAge)
	}

	return &model.RefreshResponse{
		AccessToken: res.AccessToken,
		ExpiresAt:   res.ExpiresAt,
		UserID:      res.UserId,
	}, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, sessionID string) (bool, error) {
	req := &pb.RevokeSessionRequest{
		SessionId: sessionID,
	}

	res, err := r.AuthClient.RevokeSession(ctx, req)
	if err != nil {
		return false, fmt.Errorf("failed to revoke session: %w", err)
	}

	// Clear refresh token cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.ClearRefreshTokenCookie(w)
	}

	return res.Success, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Get refresh token from cookie
	var refreshToken string
	if req, ok := appcontext.GetHTTPRequest(ctx); ok {
		if token, err := cookie.GetRefreshTokenFromCookie(req); err == nil {
			refreshToken = token
		}
	}

	if refreshToken == "" {
		return false, fmt.Errorf("no active session found")
	}

	// Revoke session using refresh token
	req := &pb.RevokeSessionByRefreshTokenRequest{
		RefreshToken: refreshToken,
	}

	res, err := r.AuthClient.RevokeSessionByRefreshToken(ctx, req)
	if err != nil {
		return false, fmt.Errorf("failed to logout: %w", err)
	}

	// Clear refresh token cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.ClearRefreshTokenCookie(w)
	}

	return res.Success, nil
}

// GetNonce is the resolver for the getNonce field.
func (r *queryResolver) GetNonce(ctx context.Context, accountID string, chainID string, domain string) (*model.Nonce, error) {
	req := &pb.GetNonceRequest{
		AccountId: accountID,
		ChainId:   chainID,
		Domain:    domain,
	}

	res, err := r.AuthClient.GetNonce(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get nonce: %w", err)
	}

	return &model.Nonce{
		Nonce:     res.Nonce,
		ExpiresAt: res.ExpiresAt,
	}, nil
}
