package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/graph/model"
	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/mapper"
	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/middleware"
	pb "github.com/zunokit/zuno-marketplace-api/shared/proto/pb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CreateCollectionInput) (*model.Collection, error) {
	// Get user ID from context (auth middleware)
	userID := middleware.GetUserIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unauthorized: authentication required")
	}

	// Convert GraphQL input to proto request
	req := mapper.GraphQLCreateInputToProto(input, userID)

	// Call collection service
	resp, err := r.CollectionClient.CreateCollection(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to create collection: %w", err)
	}

	// Convert proto to GraphQL model
	return mapper.ProtoToGraphQLCollection(resp.Collection), nil
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, id string, input model.UpdateCollectionInput) (*model.Collection, error) {
	// Get user ID from context (auth middleware)
	userID := middleware.GetUserIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unauthorized: authentication required")
	}

	// Convert GraphQL input to proto request
	req := mapper.GraphQLUpdateInputToProto(id, userID, input)

	// Call collection service (ownership check happens in service)
	resp, err := r.CollectionClient.UpdateCollection(ctx, req)
	if err != nil {
		st, ok := status.FromError(err)
		if ok && st.Code() == codes.PermissionDenied {
			return nil, fmt.Errorf("permission denied: you don't own this collection")
		}
		return nil, fmt.Errorf("failed to update collection: %w", err)
	}

	// Convert proto to GraphQL model
	return mapper.ProtoToGraphQLCollection(resp.Collection), nil
}

// AddToAllowlist is the resolver for the addToAllowlist field.
func (r *mutationResolver) AddToAllowlist(ctx context.Context, input model.AddToAllowlistInput) (bool, error) {
	// Get user ID from context (auth middleware)
	userID := middleware.GetUserIDFromContext(ctx)
	if userID == "" {
		return false, fmt.Errorf("unauthorized: authentication required")
	}

	// Build request
	req := &pb.AddToAllowlistRequest{
		CollectionId:    input.CollectionID,
		UserId:          userID,
		WalletAddresses: input.WalletAddresses,
		MaxMintAmount:   int32(input.MaxMintAmount),
	}

	// Call collection service (ownership check happens in service)
	_, err := r.CollectionClient.AddToAllowlist(ctx, req)
	if err != nil {
		st, ok := status.FromError(err)
		if ok && st.Code() == codes.PermissionDenied {
			return false, fmt.Errorf("permission denied: you don't own this collection")
		}
		return false, fmt.Errorf("failed to add to allowlist: %w", err)
	}

	return true, nil
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, id string) (bool, error) {
	// Get user ID from context (auth middleware)
	userID := middleware.GetUserIDFromContext(ctx)
	if userID == "" {
		return false, fmt.Errorf("unauthorized: authentication required")
	}

	// Build request
	req := &pb.DeleteCollectionRequest{
		Id:     id,
		UserId: userID,
	}

	// Call collection service (ownership check happens in service)
	_, err := r.CollectionClient.DeleteCollection(ctx, req)
	if err != nil {
		st, ok := status.FromError(err)
		if ok && st.Code() == codes.PermissionDenied {
			return false, fmt.Errorf("permission denied: you don't own this collection")
		}
		return false, fmt.Errorf("failed to delete collection: %w", err)
	}

	return true, nil
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, id *string, slug *string, contractAddress *string, chainID *string) (*model.Collection, error) {
	// Build request with provided parameters
	req := &pb.GetCollectionRequest{}

	if id != nil {
		req.Id = *id
	}
	if slug != nil {
		req.Slug = *slug
	}
	if contractAddress != nil {
		req.ContractAddress = *contractAddress
	}
	if chainID != nil {
		req.ChainId = *chainID
	}

	// Call collection service
	resp, err := r.CollectionClient.GetCollection(ctx, req)
	if err != nil {
		st, ok := status.FromError(err)
		if ok && st.Code() == codes.NotFound {
			return nil, nil // Return nil instead of error for not found
		}
		return nil, fmt.Errorf("failed to get collection: %w", err)
	}

	// Convert proto to GraphQL model
	return mapper.ProtoToGraphQLCollection(resp.Collection), nil
}

// MyCollections is the resolver for the myCollections field.
func (r *queryResolver) MyCollections(ctx context.Context, page *int, limit *int) (*model.CollectionConnection, error) {
	// Get user ID from context (auth middleware)
	userID := middleware.GetUserIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unauthorized: authentication required")
	}

	// Default pagination values
	pageNum := 1
	limitNum := 10

	if page != nil && *page > 0 {
		pageNum = *page
	}
	if limit != nil && *limit > 0 {
		limitNum = *limit
	}

	// Call collection service
	req := &pb.ListCollectionsByUserRequest{
		UserId: userID,
		Page:   int32(pageNum),
		Limit:  int32(limitNum),
	}

	resp, err := r.CollectionClient.ListCollectionsByUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to list collections: %w", err)
	}

	// Convert proto collections to GraphQL models
	items := make([]*model.Collection, 0, len(resp.Collections))
	for _, protoCollection := range resp.Collections {
		items = append(items, mapper.ProtoToGraphQLCollection(protoCollection))
	}

	// Calculate pagination info
	totalPages := int(resp.TotalCount) / limitNum
	if int(resp.TotalCount)%limitNum != 0 {
		totalPages++
	}

	return &model.CollectionConnection{
		Items: items,
		PageInfo: &model.PageInfo{
			TotalCount:  int(resp.TotalCount),
			Page:        pageNum,
			Limit:       limitNum,
			HasNext:     pageNum < totalPages,
			HasPrevious: pageNum > 1,
		},
	}, nil
}

// Collections is the resolver for the collections field.
func (r *queryResolver) Collections(ctx context.Context, page *int, limit *int, sortBy *string, sortOrder *string, category *string, chainID *string, isVerified *bool, searchQuery *string) (*model.CollectionConnection, error) {
	// Default pagination values
	pageNum := 1
	limitNum := 10

	if page != nil && *page > 0 {
		pageNum = *page
	}
	if limit != nil && *limit > 0 {
		limitNum = *limit
	}

	// Build request
	req := &pb.ListCollectionsRequest{
		Page:  int32(pageNum),
		Limit: int32(limitNum),
	}

	if sortBy != nil {
		req.SortBy = *sortBy
	}
	if sortOrder != nil {
		req.SortOrder = *sortOrder
	}
	if category != nil {
		req.Category = *category
	}
	if chainID != nil {
		req.ChainId = *chainID
	}
	if isVerified != nil {
		req.IsVerified = isVerified
	}
	if searchQuery != nil {
		req.SearchQuery = *searchQuery
	}

	// Call collection service
	resp, err := r.CollectionClient.ListCollections(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to list collections: %w", err)
	}

	// Convert proto collections to GraphQL models
	items := make([]*model.Collection, 0, len(resp.Collections))
	for _, protoCollection := range resp.Collections {
		items = append(items, mapper.ProtoToGraphQLCollection(protoCollection))
	}

	// Calculate pagination info
	totalPages := int(resp.TotalCount) / limitNum
	if int(resp.TotalCount)%limitNum != 0 {
		totalPages++
	}

	return &model.CollectionConnection{
		Items: items,
		PageInfo: &model.PageInfo{
			TotalCount:  int(resp.TotalCount),
			Page:        pageNum,
			Limit:       limitNum,
			HasNext:     pageNum < totalPages,
			HasPrevious: pageNum > 1,
		},
	}, nil
}
