package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/quangdang46/NFT-Marketplace/services/graphql-gateway/graph/model"
	appcontext "github.com/quangdang46/NFT-Marketplace/services/graphql-gateway/internal/context"
	"github.com/quangdang46/NFT-Marketplace/services/graphql-gateway/internal/cookie"
	pb "github.com/quangdang46/NFT-Marketplace/shared/proto/pb"
)

// VerifySiwe is the resolver for the verifySiwe field.
func (r *mutationResolver) VerifySiwe(ctx context.Context, accountID string, message string, signature string) (*model.AuthResponse, error) {
	req := &pb.VerifySiweRequest{
		AccountId: accountID,
		Message:   message,
		Signature: signature,
	}

	res, err := r.AuthClient.VerifySiwe(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to verify SIWE: %w", err)
	}

	// Set refresh token as HTTP-only cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.SetRefreshTokenCookie(w, res.RefreshToken, cookie.MaxAge)
	}

	return &model.AuthResponse{
		AccessToken:  res.AccessToken,
		RefreshToken: "", // Don't return refresh token in response body
		ExpiresAt:    res.ExpiresAt,
		UserID:       res.UserId,
		Address:      res.Address,
		ChainID:      res.ChainId,
	}, nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context, refreshToken string, userAgent *string, ipAddress *string) (*model.RefreshResponse, error) {
	// Try to get refresh token from cookie if not provided
	token := refreshToken
	if token == "" {
		if req, ok := appcontext.GetHTTPRequest(ctx); ok {
			if cookieToken, err := cookie.GetRefreshTokenFromCookie(req); err == nil {
				token = cookieToken
			}
		}
	}

	if token == "" {
		return nil, fmt.Errorf("refresh token required (either in parameter or cookie)")
	}

	req := &pb.RefreshSessionRequest{
		RefreshToken: token,
	}
	if userAgent != nil {
		req.UserAgent = *userAgent
	}
	if ipAddress != nil {
		req.IpAddress = *ipAddress
	}

	res, err := r.AuthClient.RefreshSession(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to refresh session: %w", err)
	}

	// Update refresh token cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.SetRefreshTokenCookie(w, res.RefreshToken, cookie.MaxAge)
	}

	return &model.RefreshResponse{
		AccessToken:  res.AccessToken,
		RefreshToken: "", // Don't return refresh token in response body
		ExpiresAt:    res.ExpiresAt,
		UserID:       res.UserId,
	}, nil
}

// RevokeSession is the resolver for the revokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, sessionID string) (bool, error) {
	req := &pb.RevokeSessionRequest{
		SessionId: sessionID,
	}

	res, err := r.AuthClient.RevokeSession(ctx, req)
	if err != nil {
		return false, fmt.Errorf("failed to revoke session: %w", err)
	}

	// Clear refresh token cookie
	if w, ok := appcontext.GetHTTPResponse(ctx); ok {
		cookie.ClearRefreshTokenCookie(w)
	}

	return res.Success, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.Profile, error) {
	req := &pb.UpsertProfileRequest{
		Profile: &pb.Profile{
			Username:    stringPtrToValue(input.Username),
			DisplayName: stringPtrToValue(input.DisplayName),
			AvatarUrl:   stringPtrToValue(input.AvatarURL),
			BannerUrl:   stringPtrToValue(input.BannerURL),
			Bio:         stringPtrToValue(input.Bio),
			Locale:      stringPtrToValue(input.Locale),
			Timezone:    stringPtrToValue(input.Timezone),
			SocialsJson: stringPtrToValue(input.SocialsJSON),
		},
	}

	res, err := r.UserClient.UpsertProfile(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	return &model.Profile{
		UserID:      res.Profile.UserId,
		Username:    valueToStringPtr(res.Profile.Username),
		DisplayName: valueToStringPtr(res.Profile.DisplayName),
		AvatarURL:   valueToStringPtr(res.Profile.AvatarUrl),
		BannerURL:   valueToStringPtr(res.Profile.BannerUrl),
		Bio:         valueToStringPtr(res.Profile.Bio),
		Locale:      valueToStringPtr(res.Profile.Locale),
		Timezone:    valueToStringPtr(res.Profile.Timezone),
		SocialsJSON: valueToStringPtr(res.Profile.SocialsJson),
		UpdatedAt:   valueToStringPtr(res.Profile.UpdatedAt),
	}, nil
}

// LinkWallet is the resolver for the linkWallet field.
func (r *mutationResolver) LinkWallet(ctx context.Context, input model.LinkWalletInput) (*model.WalletLink, error) {
	req := &pb.UpsertLinkRequest{
		AccountId: input.AccountID,
		Address:   input.Address,
		ChainId:   input.ChainID,
		IsPrimary: input.IsPrimary,
		Type:      stringPtrToValue(input.Type),
		Connector: stringPtrToValue(input.Connector),
		Label:     stringPtrToValue(input.Label),
	}

	res, err := r.WalletClient.UpsertLink(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to link wallet: %w", err)
	}

	return walletLinkFromProto(res.Link), nil
}

// GetNonce is the resolver for the getNonce field.
func (r *queryResolver) GetNonce(ctx context.Context, accountID string, chainID string, domain string) (*model.Nonce, error) {
	req := &pb.GetNonceRequest{
		AccountId: accountID,
		ChainId:   chainID,
		Domain:    domain,
	}

	res, err := r.AuthClient.GetNonce(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get nonce: %w", err)
	}

	return &model.Nonce{
		Nonce:     res.Nonce,
		ExpiresAt: res.ExpiresAt,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// TODO: Extract user ID from JWT token in Authorization header
	return nil, fmt.Errorf("authentication required - implement JWT validation first")
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, userID string) (*model.User, error) {
	req := &pb.GetUserRequest{
		UserId: userID,
	}

	res, err := r.UserClient.GetUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return &model.User{
		ID:        res.User.Id,
		Status:    res.User.Status,
		CreatedAt: res.User.CreatedAt,
		Profile:   profileFromProto(res.Profile),
	}, nil
}

// MyWallets is the resolver for the myWallets field.
func (r *queryResolver) MyWallets(ctx context.Context) ([]*model.WalletLink, error) {
	// TODO: Extract user ID from JWT token in Authorization header
	return nil, fmt.Errorf("authentication required - implement JWT validation first")
}

// GetWallets is the resolver for the getWallets field.
func (r *queryResolver) GetWallets(ctx context.Context, userID string) ([]*model.WalletLink, error) {
	req := &pb.GetWalletsRequest{
		UserId: userID,
	}

	res, err := r.WalletClient.GetWallets(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get wallets: %w", err)
	}

	wallets := make([]*model.WalletLink, len(res.Wallets))
	for i, w := range res.Wallets {
		wallets[i] = walletLinkFromProto(w)
	}
	return wallets, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
