package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/graph/model"
	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/middleware"
	"github.com/zunokit/zuno-marketplace-api/shared/proto/pb"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.Profile, error) {
	req := &pb.UpsertProfileRequest{
		Profile: &pb.Profile{
			Username:    stringPtrToValue(input.Username),
			DisplayName: stringPtrToValue(input.DisplayName),
			AvatarUrl:   stringPtrToValue(input.AvatarURL),
			BannerUrl:   stringPtrToValue(input.BannerURL),
			Bio:         stringPtrToValue(input.Bio),
			Locale:      stringPtrToValue(input.Locale),
			Timezone:    stringPtrToValue(input.Timezone),
			SocialsJson: stringPtrToValue(input.SocialsJSON),
		},
	}

	res, err := r.UserClient.UpsertProfile(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to update profile: %w", err)
	}

	return &model.Profile{
		UserID:      res.Profile.UserId,
		Username:    valueToStringPtr(res.Profile.Username),
		DisplayName: valueToStringPtr(res.Profile.DisplayName),
		AvatarURL:   valueToStringPtr(res.Profile.AvatarUrl),
		BannerURL:   valueToStringPtr(res.Profile.BannerUrl),
		Bio:         valueToStringPtr(res.Profile.Bio),
		Locale:      valueToStringPtr(res.Profile.Locale),
		Timezone:    valueToStringPtr(res.Profile.Timezone),
		SocialsJSON: valueToStringPtr(res.Profile.SocialsJson),
		UpdatedAt:   valueToStringPtr(res.Profile.UpdatedAt),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Extract user claims from context
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Fetch user from user service
	req := &pb.GetUserRequest{
		UserId: claims.UserID,
	}

	res, err := r.UserClient.GetUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return &model.User{
		ID:        res.User.Id,
		Status:    res.User.Status,
		CreatedAt: res.User.CreatedAt,
		Profile:   profileFromProto(res.Profile),
	}, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, userID string) (*model.User, error) {
	req := &pb.GetUserRequest{
		UserId: userID,
	}

	res, err := r.UserClient.GetUser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return &model.User{
		ID:        res.User.Id,
		Status:    res.User.Status,
		CreatedAt: res.User.CreatedAt,
		Profile:   profileFromProto(res.Profile),
	}, nil
}
