package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/graph/model"
	"github.com/zunokit/zuno-marketplace-api/services/graphql-gateway/internal/middleware"
	"github.com/zunokit/zuno-marketplace-api/shared/proto/pb"
)

// LinkWallet is the resolver for the linkWallet field.
func (r *mutationResolver) LinkWallet(ctx context.Context, input model.LinkWalletInput) (*model.WalletLink, error) {
	req := &pb.UpsertLinkRequest{
		AccountId: input.AccountID,
		Address:   input.Address,
		ChainId:   input.ChainID,
		IsPrimary: input.IsPrimary,
		Type:      stringPtrToValue(input.Type),
		Connector: stringPtrToValue(input.Connector),
		Label:     stringPtrToValue(input.Label),
	}

	res, err := r.WalletClient.UpsertLink(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to link wallet: %w", err)
	}

	return walletLinkFromProto(res.Link), nil
}

// MyWallets is the resolver for the myWallets field.
func (r *queryResolver) MyWallets(ctx context.Context) ([]*model.WalletLink, error) {
	// Extract user claims from context
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Fetch wallets from wallet service
	req := &pb.GetWalletsRequest{
		UserId: claims.UserID,
	}

	res, err := r.WalletClient.GetWallets(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get wallets: %w", err)
	}

	wallets := make([]*model.WalletLink, len(res.Wallets))
	for i, w := range res.Wallets {
		wallets[i] = walletLinkFromProto(w)
	}
	return wallets, nil
}

// GetWallets is the resolver for the getWallets field.
func (r *queryResolver) GetWallets(ctx context.Context, userID string) ([]*model.WalletLink, error) {
	req := &pb.GetWalletsRequest{
		UserId: userID,
	}

	res, err := r.WalletClient.GetWallets(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get wallets: %w", err)
	}

	wallets := make([]*model.WalletLink, len(res.Wallets))
	for i, w := range res.Wallets {
		wallets[i] = walletLinkFromProto(w)
	}
	return wallets, nil
}
