apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nft-marketplace/auth-service
          ports:
            - containerPort: 50051
          env:
            - name: AUTH_GRPC_PORT
              value: ":50051"
            - name: USER_SERVICE_URL
              value: "user-service:50052"
            - name: WALLET_SERVICE_URL
              value: "wallet-service:50053"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_DATABASE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_EXCHANGE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: JWT_SECRET
            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: REFRESH_SECRET
