apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: dev
spec:
  ports:
    - port: 50054
      targetPort: 50054
  selector:
    app: collection-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
  template:
    metadata:
      labels:
        app: collection-service
    spec:
      containers:
        - name: collection-service
          image: collection-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50054
          env:
            - name: COLLECTION_GRPC_PORT
              value: ":50054"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DATABASE
