apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: dev
spec:
  ports:
    - port: 50055
      targetPort: 50055
  selector:
    app: media-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: nft-marketplace/media-service
          ports:
            - containerPort: 50055
          env:
            - name: MEDIA_GRPC_PORT
              value: ":50055"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_EXCHANGE
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: MONGO_URI
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: MONGO_DATABASE
            - name: PINATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: PINATA_API_KEY
            - name: PINATA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: PINATA_SECRET_KEY
            - name: PINATA_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: PINATA_JWT_KEY
