apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: dev
spec:
  ports:
    - port: 50054
      targetPort: 50054
  selector:
    app: orchestrator-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: nft-marketplace/orchestrator-service
          ports:
            - containerPort: 50054
          env:
            - name: ORCHESTRATOR_GRPC_PORT
              value: ":50054"
            - name: CHAIN_REGISTRY_URL
              value: "chain-registry-service:50056"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: POSTGRES_DATABASE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: REDIS_PORT
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nft-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: nft-config
                  key: RABBITMQ_EXCHANGE
