// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc1
// source: proto/collection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenStandard int32

const (
	TokenStandard_TOKEN_STANDARD_UNSPECIFIED TokenStandard = 0
	TokenStandard_TOKEN_STANDARD_ERC721      TokenStandard = 1
	TokenStandard_TOKEN_STANDARD_ERC1155     TokenStandard = 2
)

// Enum value maps for TokenStandard.
var (
	TokenStandard_name = map[int32]string{
		0: "TOKEN_STANDARD_UNSPECIFIED",
		1: "TOKEN_STANDARD_ERC721",
		2: "TOKEN_STANDARD_ERC1155",
	}
	TokenStandard_value = map[string]int32{
		"TOKEN_STANDARD_UNSPECIFIED": 0,
		"TOKEN_STANDARD_ERC721":      1,
		"TOKEN_STANDARD_ERC1155":     2,
	}
)

func (x TokenStandard) Enum() *TokenStandard {
	p := new(TokenStandard)
	*p = x
	return p
}

func (x TokenStandard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenStandard) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_collection_proto_enumTypes[0].Descriptor()
}

func (TokenStandard) Type() protoreflect.EnumType {
	return &file_proto_collection_proto_enumTypes[0]
}

func (x TokenStandard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenStandard.Descriptor instead.
func (TokenStandard) EnumDescriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{0}
}

type CollectionStatus int32

const (
	CollectionStatus_COLLECTION_STATUS_UNSPECIFIED CollectionStatus = 0
	CollectionStatus_COLLECTION_STATUS_PENDING     CollectionStatus = 1
	CollectionStatus_COLLECTION_STATUS_DEPLOYED    CollectionStatus = 2
	CollectionStatus_COLLECTION_STATUS_FAILED      CollectionStatus = 3
	CollectionStatus_COLLECTION_STATUS_ARCHIVED    CollectionStatus = 4
)

// Enum value maps for CollectionStatus.
var (
	CollectionStatus_name = map[int32]string{
		0: "COLLECTION_STATUS_UNSPECIFIED",
		1: "COLLECTION_STATUS_PENDING",
		2: "COLLECTION_STATUS_DEPLOYED",
		3: "COLLECTION_STATUS_FAILED",
		4: "COLLECTION_STATUS_ARCHIVED",
	}
	CollectionStatus_value = map[string]int32{
		"COLLECTION_STATUS_UNSPECIFIED": 0,
		"COLLECTION_STATUS_PENDING":     1,
		"COLLECTION_STATUS_DEPLOYED":    2,
		"COLLECTION_STATUS_FAILED":      3,
		"COLLECTION_STATUS_ARCHIVED":    4,
	}
)

func (x CollectionStatus) Enum() *CollectionStatus {
	p := new(CollectionStatus)
	*p = x
	return p
}

func (x CollectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_collection_proto_enumTypes[1].Descriptor()
}

func (CollectionStatus) Type() protoreflect.EnumType {
	return &file_proto_collection_proto_enumTypes[1]
}

func (x CollectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionStatus.Descriptor instead.
func (CollectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{1}
}

type IndexStatus int32

const (
	IndexStatus_INDEX_STATUS_UNSPECIFIED IndexStatus = 0
	IndexStatus_INDEX_STATUS_NOT_STARTED IndexStatus = 1
	IndexStatus_INDEX_STATUS_SYNCING     IndexStatus = 2
	IndexStatus_INDEX_STATUS_SYNCED      IndexStatus = 3
	IndexStatus_INDEX_STATUS_FAILED      IndexStatus = 4
)

// Enum value maps for IndexStatus.
var (
	IndexStatus_name = map[int32]string{
		0: "INDEX_STATUS_UNSPECIFIED",
		1: "INDEX_STATUS_NOT_STARTED",
		2: "INDEX_STATUS_SYNCING",
		3: "INDEX_STATUS_SYNCED",
		4: "INDEX_STATUS_FAILED",
	}
	IndexStatus_value = map[string]int32{
		"INDEX_STATUS_UNSPECIFIED": 0,
		"INDEX_STATUS_NOT_STARTED": 1,
		"INDEX_STATUS_SYNCING":     2,
		"INDEX_STATUS_SYNCED":      3,
		"INDEX_STATUS_FAILED":      4,
	}
)

func (x IndexStatus) Enum() *IndexStatus {
	p := new(IndexStatus)
	*p = x
	return p
}

func (x IndexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_collection_proto_enumTypes[2].Descriptor()
}

func (IndexStatus) Type() protoreflect.EnumType {
	return &file_proto_collection_proto_enumTypes[2]
}

func (x IndexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexStatus.Descriptor instead.
func (IndexStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{2}
}

type Collection struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug               string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Symbol             string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description        string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Category           string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	ContractAddress    string                 `protobuf:"bytes,8,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ChainId            string                 `protobuf:"bytes,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TokenStandard      TokenStandard          `protobuf:"varint,10,opt,name=token_standard,json=tokenStandard,proto3,enum=pb.TokenStandard" json:"token_standard,omitempty"`
	DeployerAddress    string                 `protobuf:"bytes,11,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
	DeployedBlock      int64                  `protobuf:"varint,12,opt,name=deployed_block,json=deployedBlock,proto3" json:"deployed_block,omitempty"`
	Status             CollectionStatus       `protobuf:"varint,13,opt,name=status,proto3,enum=pb.CollectionStatus" json:"status,omitempty"`
	DeployedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	IndexStatus        IndexStatus            `protobuf:"varint,15,opt,name=index_status,json=indexStatus,proto3,enum=pb.IndexStatus" json:"index_status,omitempty"`
	IsVerified         bool                   `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	IsHidden           bool                   `protobuf:"varint,17,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	Source             string                 `protobuf:"bytes,18,opt,name=source,proto3" json:"source,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,19,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl          string                 `protobuf:"bytes,20,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	FeaturedImageUrl   string                 `protobuf:"bytes,21,opt,name=featured_image_url,json=featuredImageUrl,proto3" json:"featured_image_url,omitempty"`
	WebsiteUrl         string                 `protobuf:"bytes,22,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	BaseUri            string                 `protobuf:"bytes,23,opt,name=base_uri,json=baseUri,proto3" json:"base_uri,omitempty"`
	MaxSupply          int64                  `protobuf:"varint,24,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	MintPriceAllowlist string                 `protobuf:"bytes,25,opt,name=mint_price_allowlist,json=mintPriceAllowlist,proto3" json:"mint_price_allowlist,omitempty"` // Wei as string
	MintPricePublic    string                 `protobuf:"bytes,26,opt,name=mint_price_public,json=mintPricePublic,proto3" json:"mint_price_public,omitempty"`          // Wei as string
	MintStartTime      *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=mint_start_time,json=mintStartTime,proto3" json:"mint_start_time,omitempty"`
	AllowlistStageEnd  *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=allowlist_stage_end,json=allowlistStageEnd,proto3" json:"allowlist_stage_end,omitempty"`
	MintLimitPerWallet int32                  `protobuf:"varint,29,opt,name=mint_limit_per_wallet,json=mintLimitPerWallet,proto3" json:"mint_limit_per_wallet,omitempty"`
	RoyaltyFeeBps      int32                  `protobuf:"varint,30,opt,name=royalty_fee_bps,json=royaltyFeeBps,proto3" json:"royalty_fee_bps,omitempty"`
	RoyaltyRecipient   string                 `protobuf:"bytes,31,opt,name=royalty_recipient,json=royaltyRecipient,proto3" json:"royalty_recipient,omitempty"`
	TotalSupply        int32                  `protobuf:"varint,32,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	TotalMinted        int32                  `protobuf:"varint,33,opt,name=total_minted,json=totalMinted,proto3" json:"total_minted,omitempty"`
	MetadataStandard   string                 `protobuf:"bytes,34,opt,name=metadata_standard,json=metadataStandard,proto3" json:"metadata_standard,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,35,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,36,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Relations
	Metadata      *CollectionMetadata `protobuf:"bytes,37,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Stats         *CollectionStats    `protobuf:"bytes,38,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_proto_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{0}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Collection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collection) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Collection) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Collection) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Collection) GetTokenStandard() TokenStandard {
	if x != nil {
		return x.TokenStandard
	}
	return TokenStandard_TOKEN_STANDARD_UNSPECIFIED
}

func (x *Collection) GetDeployerAddress() string {
	if x != nil {
		return x.DeployerAddress
	}
	return ""
}

func (x *Collection) GetDeployedBlock() int64 {
	if x != nil {
		return x.DeployedBlock
	}
	return 0
}

func (x *Collection) GetStatus() CollectionStatus {
	if x != nil {
		return x.Status
	}
	return CollectionStatus_COLLECTION_STATUS_UNSPECIFIED
}

func (x *Collection) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *Collection) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_UNSPECIFIED
}

func (x *Collection) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Collection) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Collection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Collection) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Collection) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *Collection) GetFeaturedImageUrl() string {
	if x != nil {
		return x.FeaturedImageUrl
	}
	return ""
}

func (x *Collection) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *Collection) GetBaseUri() string {
	if x != nil {
		return x.BaseUri
	}
	return ""
}

func (x *Collection) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *Collection) GetMintPriceAllowlist() string {
	if x != nil {
		return x.MintPriceAllowlist
	}
	return ""
}

func (x *Collection) GetMintPricePublic() string {
	if x != nil {
		return x.MintPricePublic
	}
	return ""
}

func (x *Collection) GetMintStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MintStartTime
	}
	return nil
}

func (x *Collection) GetAllowlistStageEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.AllowlistStageEnd
	}
	return nil
}

func (x *Collection) GetMintLimitPerWallet() int32 {
	if x != nil {
		return x.MintLimitPerWallet
	}
	return 0
}

func (x *Collection) GetRoyaltyFeeBps() int32 {
	if x != nil {
		return x.RoyaltyFeeBps
	}
	return 0
}

func (x *Collection) GetRoyaltyRecipient() string {
	if x != nil {
		return x.RoyaltyRecipient
	}
	return ""
}

func (x *Collection) GetTotalSupply() int32 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *Collection) GetTotalMinted() int32 {
	if x != nil {
		return x.TotalMinted
	}
	return 0
}

func (x *Collection) GetMetadataStandard() string {
	if x != nil {
		return x.MetadataStandard
	}
	return ""
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Collection) GetMetadata() *CollectionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Collection) GetStats() *CollectionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CollectionMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId    string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	MetadataUri     string                 `protobuf:"bytes,3,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	IpfsHash        string                 `protobuf:"bytes,4,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	IpfsUrl         string                 `protobuf:"bytes,5,opt,name=ipfs_url,json=ipfsUrl,proto3" json:"ipfs_url,omitempty"`
	DiscordUrl      string                 `protobuf:"bytes,6,opt,name=discord_url,json=discordUrl,proto3" json:"discord_url,omitempty"`
	TwitterUrl      string                 `protobuf:"bytes,7,opt,name=twitter_url,json=twitterUrl,proto3" json:"twitter_url,omitempty"`
	InstagramUrl    string                 `protobuf:"bytes,8,opt,name=instagram_url,json=instagramUrl,proto3" json:"instagram_url,omitempty"`
	MediumUrl       string                 `protobuf:"bytes,9,opt,name=medium_url,json=mediumUrl,proto3" json:"medium_url,omitempty"`
	TelegramUrl     string                 `protobuf:"bytes,10,opt,name=telegram_url,json=telegramUrl,proto3" json:"telegram_url,omitempty"`
	BackgroundColor string                 `protobuf:"bytes,11,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectionMetadata) Reset() {
	*x = CollectionMetadata{}
	mi := &file_proto_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionMetadata) ProtoMessage() {}

func (x *CollectionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionMetadata.ProtoReflect.Descriptor instead.
func (*CollectionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectionMetadata) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CollectionMetadata) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *CollectionMetadata) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *CollectionMetadata) GetIpfsUrl() string {
	if x != nil {
		return x.IpfsUrl
	}
	return ""
}

func (x *CollectionMetadata) GetDiscordUrl() string {
	if x != nil {
		return x.DiscordUrl
	}
	return ""
}

func (x *CollectionMetadata) GetTwitterUrl() string {
	if x != nil {
		return x.TwitterUrl
	}
	return ""
}

func (x *CollectionMetadata) GetInstagramUrl() string {
	if x != nil {
		return x.InstagramUrl
	}
	return ""
}

func (x *CollectionMetadata) GetMediumUrl() string {
	if x != nil {
		return x.MediumUrl
	}
	return ""
}

func (x *CollectionMetadata) GetTelegramUrl() string {
	if x != nil {
		return x.TelegramUrl
	}
	return ""
}

func (x *CollectionMetadata) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

type CollectionStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectionId    string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	TotalItems      int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalOwners     int32                  `protobuf:"varint,3,opt,name=total_owners,json=totalOwners,proto3" json:"total_owners,omitempty"`
	TotalSales      int32                  `protobuf:"varint,4,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	FloorPriceWei   string                 `protobuf:"bytes,5,opt,name=floor_price_wei,json=floorPriceWei,proto3" json:"floor_price_wei,omitempty"`
	TotalVolumeWei  string                 `protobuf:"bytes,6,opt,name=total_volume_wei,json=totalVolumeWei,proto3" json:"total_volume_wei,omitempty"`
	AveragePriceWei string                 `protobuf:"bytes,7,opt,name=average_price_wei,json=averagePriceWei,proto3" json:"average_price_wei,omitempty"`
	Volume_24HWei   string                 `protobuf:"bytes,8,opt,name=volume_24h_wei,json=volume24hWei,proto3" json:"volume_24h_wei,omitempty"`
	Sales_24H       int32                  `protobuf:"varint,9,opt,name=sales_24h,json=sales24h,proto3" json:"sales_24h,omitempty"`
	LastSaleAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_sale_at,json=lastSaleAt,proto3" json:"last_sale_at,omitempty"`
	LastMintAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_mint_at,json=lastMintAt,proto3" json:"last_mint_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CollectionStats) Reset() {
	*x = CollectionStats{}
	mi := &file_proto_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStats) ProtoMessage() {}

func (x *CollectionStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStats.ProtoReflect.Descriptor instead.
func (*CollectionStats) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionStats) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CollectionStats) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *CollectionStats) GetTotalOwners() int32 {
	if x != nil {
		return x.TotalOwners
	}
	return 0
}

func (x *CollectionStats) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *CollectionStats) GetFloorPriceWei() string {
	if x != nil {
		return x.FloorPriceWei
	}
	return ""
}

func (x *CollectionStats) GetTotalVolumeWei() string {
	if x != nil {
		return x.TotalVolumeWei
	}
	return ""
}

func (x *CollectionStats) GetAveragePriceWei() string {
	if x != nil {
		return x.AveragePriceWei
	}
	return ""
}

func (x *CollectionStats) GetVolume_24HWei() string {
	if x != nil {
		return x.Volume_24HWei
	}
	return ""
}

func (x *CollectionStats) GetSales_24H() int32 {
	if x != nil {
		return x.Sales_24H
	}
	return 0
}

func (x *CollectionStats) GetLastSaleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSaleAt
	}
	return nil
}

func (x *CollectionStats) GetLastMintAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMintAt
	}
	return nil
}

func (x *CollectionStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CollectionAllowlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	MaxMintAmount int32                  `protobuf:"varint,4,opt,name=max_mint_amount,json=maxMintAmount,proto3" json:"max_mint_amount,omitempty"`
	AddedByUserId string                 `protobuf:"bytes,5,opt,name=added_by_user_id,json=addedByUserId,proto3" json:"added_by_user_id,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionAllowlist) Reset() {
	*x = CollectionAllowlist{}
	mi := &file_proto_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionAllowlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionAllowlist) ProtoMessage() {}

func (x *CollectionAllowlist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionAllowlist.ProtoReflect.Descriptor instead.
func (*CollectionAllowlist) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionAllowlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectionAllowlist) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *CollectionAllowlist) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *CollectionAllowlist) GetMaxMintAmount() int32 {
	if x != nil {
		return x.MaxMintAmount
	}
	return 0
}

func (x *CollectionAllowlist) GetAddedByUserId() string {
	if x != nil {
		return x.AddedByUserId
	}
	return ""
}

func (x *CollectionAllowlist) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type CreateCollectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol             string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category           string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	TokenStandard      TokenStandard          `protobuf:"varint,6,opt,name=token_standard,json=tokenStandard,proto3,enum=pb.TokenStandard" json:"token_standard,omitempty"`
	DeployerAddress    string                 `protobuf:"bytes,7,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
	ChainId            string                 `protobuf:"bytes,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BannerUrl          string                 `protobuf:"bytes,10,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	FeaturedImageUrl   string                 `protobuf:"bytes,11,opt,name=featured_image_url,json=featuredImageUrl,proto3" json:"featured_image_url,omitempty"`
	WebsiteUrl         string                 `protobuf:"bytes,12,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	RoyaltyFeeBps      int32                  `protobuf:"varint,13,opt,name=royalty_fee_bps,json=royaltyFeeBps,proto3" json:"royalty_fee_bps,omitempty"`
	RoyaltyRecipient   string                 `protobuf:"bytes,14,opt,name=royalty_recipient,json=royaltyRecipient,proto3" json:"royalty_recipient,omitempty"`
	BaseUri            string                 `protobuf:"bytes,15,opt,name=base_uri,json=baseUri,proto3" json:"base_uri,omitempty"`
	MaxSupply          int64                  `protobuf:"varint,16,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	MintPriceAllowlist string                 `protobuf:"bytes,17,opt,name=mint_price_allowlist,json=mintPriceAllowlist,proto3" json:"mint_price_allowlist,omitempty"`
	MintPricePublic    string                 `protobuf:"bytes,18,opt,name=mint_price_public,json=mintPricePublic,proto3" json:"mint_price_public,omitempty"`
	MintStartTime      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=mint_start_time,json=mintStartTime,proto3" json:"mint_start_time,omitempty"`
	AllowlistStageEnd  *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=allowlist_stage_end,json=allowlistStageEnd,proto3" json:"allowlist_stage_end,omitempty"`
	MintLimitPerWallet int32                  `protobuf:"varint,21,opt,name=mint_limit_per_wallet,json=mintLimitPerWallet,proto3" json:"mint_limit_per_wallet,omitempty"`
	// Metadata
	MetadataUri   string `protobuf:"bytes,22,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	IpfsHash      string `protobuf:"bytes,23,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	DiscordUrl    string `protobuf:"bytes,24,opt,name=discord_url,json=discordUrl,proto3" json:"discord_url,omitempty"`
	TwitterUrl    string `protobuf:"bytes,25,opt,name=twitter_url,json=twitterUrl,proto3" json:"twitter_url,omitempty"`
	InstagramUrl  string `protobuf:"bytes,26,opt,name=instagram_url,json=instagramUrl,proto3" json:"instagram_url,omitempty"`
	MediumUrl     string `protobuf:"bytes,27,opt,name=medium_url,json=mediumUrl,proto3" json:"medium_url,omitempty"`
	TelegramUrl   string `protobuf:"bytes,28,opt,name=telegram_url,json=telegramUrl,proto3" json:"telegram_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_proto_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCollectionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateCollectionRequest) GetTokenStandard() TokenStandard {
	if x != nil {
		return x.TokenStandard
	}
	return TokenStandard_TOKEN_STANDARD_UNSPECIFIED
}

func (x *CreateCollectionRequest) GetDeployerAddress() string {
	if x != nil {
		return x.DeployerAddress
	}
	return ""
}

func (x *CreateCollectionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateCollectionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetFeaturedImageUrl() string {
	if x != nil {
		return x.FeaturedImageUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetRoyaltyFeeBps() int32 {
	if x != nil {
		return x.RoyaltyFeeBps
	}
	return 0
}

func (x *CreateCollectionRequest) GetRoyaltyRecipient() string {
	if x != nil {
		return x.RoyaltyRecipient
	}
	return ""
}

func (x *CreateCollectionRequest) GetBaseUri() string {
	if x != nil {
		return x.BaseUri
	}
	return ""
}

func (x *CreateCollectionRequest) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *CreateCollectionRequest) GetMintPriceAllowlist() string {
	if x != nil {
		return x.MintPriceAllowlist
	}
	return ""
}

func (x *CreateCollectionRequest) GetMintPricePublic() string {
	if x != nil {
		return x.MintPricePublic
	}
	return ""
}

func (x *CreateCollectionRequest) GetMintStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MintStartTime
	}
	return nil
}

func (x *CreateCollectionRequest) GetAllowlistStageEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.AllowlistStageEnd
	}
	return nil
}

func (x *CreateCollectionRequest) GetMintLimitPerWallet() int32 {
	if x != nil {
		return x.MintLimitPerWallet
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *CreateCollectionRequest) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *CreateCollectionRequest) GetDiscordUrl() string {
	if x != nil {
		return x.DiscordUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetTwitterUrl() string {
	if x != nil {
		return x.TwitterUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetInstagramUrl() string {
	if x != nil {
		return x.InstagramUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetMediumUrl() string {
	if x != nil {
		return x.MediumUrl
	}
	return ""
}

func (x *CreateCollectionRequest) GetTelegramUrl() string {
	if x != nil {
		return x.TelegramUrl
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_proto_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type GetCollectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug            string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	ContractAddress string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ChainId         string                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_proto_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{6}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectionRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetCollectionRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetCollectionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type GetCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionResponse) Reset() {
	*x = GetCollectionResponse{}
	mi := &file_proto_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionResponse) ProtoMessage() {}

func (x *GetCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{7}
}

func (x *GetCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type UpdateCollectionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	// Updateable fields
	Description      *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Category         *string `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`
	ImageUrl         *string `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	BannerUrl        *string `protobuf:"bytes,6,opt,name=banner_url,json=bannerUrl,proto3,oneof" json:"banner_url,omitempty"`
	FeaturedImageUrl *string `protobuf:"bytes,7,opt,name=featured_image_url,json=featuredImageUrl,proto3,oneof" json:"featured_image_url,omitempty"`
	WebsiteUrl       *string `protobuf:"bytes,8,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	DiscordUrl       *string `protobuf:"bytes,9,opt,name=discord_url,json=discordUrl,proto3,oneof" json:"discord_url,omitempty"`
	TwitterUrl       *string `protobuf:"bytes,10,opt,name=twitter_url,json=twitterUrl,proto3,oneof" json:"twitter_url,omitempty"`
	InstagramUrl     *string `protobuf:"bytes,11,opt,name=instagram_url,json=instagramUrl,proto3,oneof" json:"instagram_url,omitempty"`
	MediumUrl        *string `protobuf:"bytes,12,opt,name=medium_url,json=mediumUrl,proto3,oneof" json:"medium_url,omitempty"`
	TelegramUrl      *string `protobuf:"bytes,13,opt,name=telegram_url,json=telegramUrl,proto3,oneof" json:"telegram_url,omitempty"`
	BackgroundColor  *string `protobuf:"bytes,14,opt,name=background_color,json=backgroundColor,proto3,oneof" json:"background_color,omitempty"`
	// Mint settings
	BaseUri            *string                `protobuf:"bytes,15,opt,name=base_uri,json=baseUri,proto3,oneof" json:"base_uri,omitempty"`
	MintPriceAllowlist *string                `protobuf:"bytes,16,opt,name=mint_price_allowlist,json=mintPriceAllowlist,proto3,oneof" json:"mint_price_allowlist,omitempty"`
	MintPricePublic    *string                `protobuf:"bytes,17,opt,name=mint_price_public,json=mintPricePublic,proto3,oneof" json:"mint_price_public,omitempty"`
	MintStartTime      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=mint_start_time,json=mintStartTime,proto3,oneof" json:"mint_start_time,omitempty"`
	AllowlistStageEnd  *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=allowlist_stage_end,json=allowlistStageEnd,proto3,oneof" json:"allowlist_stage_end,omitempty"`
	MintLimitPerWallet *int32                 `protobuf:"varint,20,opt,name=mint_limit_per_wallet,json=mintLimitPerWallet,proto3,oneof" json:"mint_limit_per_wallet,omitempty"`
	// Status update (e.g. after deployment)
	Status          *CollectionStatus `protobuf:"varint,21,opt,name=status,proto3,enum=pb.CollectionStatus,oneof" json:"status,omitempty"`
	ContractAddress *string           `protobuf:"bytes,22,opt,name=contract_address,json=contractAddress,proto3,oneof" json:"contract_address,omitempty"`
	DeployedBlock   *int64            `protobuf:"varint,23,opt,name=deployed_block,json=deployedBlock,proto3,oneof" json:"deployed_block,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_proto_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCollectionRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateCollectionRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetBannerUrl() string {
	if x != nil && x.BannerUrl != nil {
		return *x.BannerUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetFeaturedImageUrl() string {
	if x != nil && x.FeaturedImageUrl != nil {
		return *x.FeaturedImageUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDiscordUrl() string {
	if x != nil && x.DiscordUrl != nil {
		return *x.DiscordUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetTwitterUrl() string {
	if x != nil && x.TwitterUrl != nil {
		return *x.TwitterUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetInstagramUrl() string {
	if x != nil && x.InstagramUrl != nil {
		return *x.InstagramUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetMediumUrl() string {
	if x != nil && x.MediumUrl != nil {
		return *x.MediumUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetTelegramUrl() string {
	if x != nil && x.TelegramUrl != nil {
		return *x.TelegramUrl
	}
	return ""
}

func (x *UpdateCollectionRequest) GetBackgroundColor() string {
	if x != nil && x.BackgroundColor != nil {
		return *x.BackgroundColor
	}
	return ""
}

func (x *UpdateCollectionRequest) GetBaseUri() string {
	if x != nil && x.BaseUri != nil {
		return *x.BaseUri
	}
	return ""
}

func (x *UpdateCollectionRequest) GetMintPriceAllowlist() string {
	if x != nil && x.MintPriceAllowlist != nil {
		return *x.MintPriceAllowlist
	}
	return ""
}

func (x *UpdateCollectionRequest) GetMintPricePublic() string {
	if x != nil && x.MintPricePublic != nil {
		return *x.MintPricePublic
	}
	return ""
}

func (x *UpdateCollectionRequest) GetMintStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MintStartTime
	}
	return nil
}

func (x *UpdateCollectionRequest) GetAllowlistStageEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.AllowlistStageEnd
	}
	return nil
}

func (x *UpdateCollectionRequest) GetMintLimitPerWallet() int32 {
	if x != nil && x.MintLimitPerWallet != nil {
		return *x.MintLimitPerWallet
	}
	return 0
}

func (x *UpdateCollectionRequest) GetStatus() CollectionStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CollectionStatus_COLLECTION_STATUS_UNSPECIFIED
}

func (x *UpdateCollectionRequest) GetContractAddress() string {
	if x != nil && x.ContractAddress != nil {
		return *x.ContractAddress
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDeployedBlock() int64 {
	if x != nil && x.DeployedBlock != nil {
		return *x.DeployedBlock
	}
	return 0
}

type UpdateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionResponse) Reset() {
	*x = UpdateCollectionResponse{}
	mi := &file_proto_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionResponse) ProtoMessage() {}

func (x *UpdateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type ListCollectionsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsByUserRequest) Reset() {
	*x = ListCollectionsByUserRequest{}
	mi := &file_proto_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsByUserRequest) ProtoMessage() {}

func (x *ListCollectionsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{10}
}

func (x *ListCollectionsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCollectionsByUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // "created_at", "volume", "floor_price"
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc", "desc"
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ChainId       string                 `protobuf:"bytes,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IsVerified    *bool                  `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3,oneof" json:"is_verified,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,8,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_proto_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{11}
}

func (x *ListCollectionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCollectionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListCollectionsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListCollectionsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListCollectionsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ListCollectionsRequest) GetIsVerified() bool {
	if x != nil && x.IsVerified != nil {
		return *x.IsVerified
	}
	return false
}

func (x *ListCollectionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_proto_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{12}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCollectionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AddToAllowlistRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectionId    string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	WalletAddresses []string               `protobuf:"bytes,3,rep,name=wallet_addresses,json=walletAddresses,proto3" json:"wallet_addresses,omitempty"`
	MaxMintAmount   int32                  `protobuf:"varint,4,opt,name=max_mint_amount,json=maxMintAmount,proto3" json:"max_mint_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddToAllowlistRequest) Reset() {
	*x = AddToAllowlistRequest{}
	mi := &file_proto_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToAllowlistRequest) ProtoMessage() {}

func (x *AddToAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToAllowlistRequest.ProtoReflect.Descriptor instead.
func (*AddToAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{13}
}

func (x *AddToAllowlistRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *AddToAllowlistRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToAllowlistRequest) GetWalletAddresses() []string {
	if x != nil {
		return x.WalletAddresses
	}
	return nil
}

func (x *AddToAllowlistRequest) GetMaxMintAmount() int32 {
	if x != nil {
		return x.MaxMintAmount
	}
	return 0
}

type AddToAllowlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddedCount    int32                  `protobuf:"varint,1,opt,name=added_count,json=addedCount,proto3" json:"added_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToAllowlistResponse) Reset() {
	*x = AddToAllowlistResponse{}
	mi := &file_proto_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToAllowlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToAllowlistResponse) ProtoMessage() {}

func (x *AddToAllowlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToAllowlistResponse.ProtoReflect.Descriptor instead.
func (*AddToAllowlistResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{14}
}

func (x *AddToAllowlistResponse) GetAddedCount() int32 {
	if x != nil {
		return x.AddedCount
	}
	return 0
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_proto_collection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionResponse) Reset() {
	*x = DeleteCollectionResponse{}
	mi := &file_proto_collection_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionResponse) ProtoMessage() {}

func (x *DeleteCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Indexer Webhook Request/Response
type ProcessIndexerWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`                       // e.g., "collection.created"
	ChainId       int64                  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`   // Chain ID (e.g., 31337)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Block timestamp
	DataJson      string                 `protobuf:"bytes,4,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // JSON-encoded event data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessIndexerWebhookRequest) Reset() {
	*x = ProcessIndexerWebhookRequest{}
	mi := &file_proto_collection_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessIndexerWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessIndexerWebhookRequest) ProtoMessage() {}

func (x *ProcessIndexerWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessIndexerWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessIndexerWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessIndexerWebhookRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ProcessIndexerWebhookRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ProcessIndexerWebhookRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessIndexerWebhookRequest) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ProcessIndexerWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessIndexerWebhookResponse) Reset() {
	*x = ProcessIndexerWebhookResponse{}
	mi := &file_proto_collection_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessIndexerWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessIndexerWebhookResponse) ProtoMessage() {}

func (x *ProcessIndexerWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collection_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessIndexerWebhookResponse.ProtoReflect.Descriptor instead.
func (*ProcessIndexerWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_collection_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessIndexerWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessIndexerWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_collection_proto protoreflect.FileDescriptor

const file_proto_collection_proto_rawDesc = "" +
	"\n" +
	"\x16proto/collection.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\v\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12)\n" +
	"\x10contract_address\x18\b \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\bchain_id\x18\t \x01(\tR\achainId\x128\n" +
	"\x0etoken_standard\x18\n" +
	" \x01(\x0e2\x11.pb.TokenStandardR\rtokenStandard\x12)\n" +
	"\x10deployer_address\x18\v \x01(\tR\x0fdeployerAddress\x12%\n" +
	"\x0edeployed_block\x18\f \x01(\x03R\rdeployedBlock\x12,\n" +
	"\x06status\x18\r \x01(\x0e2\x14.pb.CollectionStatusR\x06status\x12;\n" +
	"\vdeployed_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x122\n" +
	"\findex_status\x18\x0f \x01(\x0e2\x0f.pb.IndexStatusR\vindexStatus\x12\x1f\n" +
	"\vis_verified\x18\x10 \x01(\bR\n" +
	"isVerified\x12\x1b\n" +
	"\tis_hidden\x18\x11 \x01(\bR\bisHidden\x12\x16\n" +
	"\x06source\x18\x12 \x01(\tR\x06source\x12\x1b\n" +
	"\timage_url\x18\x13 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x14 \x01(\tR\tbannerUrl\x12,\n" +
	"\x12featured_image_url\x18\x15 \x01(\tR\x10featuredImageUrl\x12\x1f\n" +
	"\vwebsite_url\x18\x16 \x01(\tR\n" +
	"websiteUrl\x12\x19\n" +
	"\bbase_uri\x18\x17 \x01(\tR\abaseUri\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x18 \x01(\x03R\tmaxSupply\x120\n" +
	"\x14mint_price_allowlist\x18\x19 \x01(\tR\x12mintPriceAllowlist\x12*\n" +
	"\x11mint_price_public\x18\x1a \x01(\tR\x0fmintPricePublic\x12B\n" +
	"\x0fmint_start_time\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\rmintStartTime\x12J\n" +
	"\x13allowlist_stage_end\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\x11allowlistStageEnd\x121\n" +
	"\x15mint_limit_per_wallet\x18\x1d \x01(\x05R\x12mintLimitPerWallet\x12&\n" +
	"\x0froyalty_fee_bps\x18\x1e \x01(\x05R\rroyaltyFeeBps\x12+\n" +
	"\x11royalty_recipient\x18\x1f \x01(\tR\x10royaltyRecipient\x12!\n" +
	"\ftotal_supply\x18  \x01(\x05R\vtotalSupply\x12!\n" +
	"\ftotal_minted\x18! \x01(\x05R\vtotalMinted\x12+\n" +
	"\x11metadata_standard\x18\" \x01(\tR\x10metadataStandard\x129\n" +
	"\n" +
	"created_at\x18# \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18$ \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\bmetadata\x18% \x01(\v2\x16.pb.CollectionMetadataR\bmetadata\x12)\n" +
	"\x05stats\x18& \x01(\v2\x13.pb.CollectionStatsR\x05stats\"\xf8\x02\n" +
	"\x12CollectionMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12!\n" +
	"\fmetadata_uri\x18\x03 \x01(\tR\vmetadataUri\x12\x1b\n" +
	"\tipfs_hash\x18\x04 \x01(\tR\bipfsHash\x12\x19\n" +
	"\bipfs_url\x18\x05 \x01(\tR\aipfsUrl\x12\x1f\n" +
	"\vdiscord_url\x18\x06 \x01(\tR\n" +
	"discordUrl\x12\x1f\n" +
	"\vtwitter_url\x18\a \x01(\tR\n" +
	"twitterUrl\x12#\n" +
	"\rinstagram_url\x18\b \x01(\tR\finstagramUrl\x12\x1d\n" +
	"\n" +
	"medium_url\x18\t \x01(\tR\tmediumUrl\x12!\n" +
	"\ftelegram_url\x18\n" +
	" \x01(\tR\vtelegramUrl\x12)\n" +
	"\x10background_color\x18\v \x01(\tR\x0fbackgroundColor\"\x93\x04\n" +
	"\x0fCollectionStats\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12!\n" +
	"\ftotal_owners\x18\x03 \x01(\x05R\vtotalOwners\x12\x1f\n" +
	"\vtotal_sales\x18\x04 \x01(\x05R\n" +
	"totalSales\x12&\n" +
	"\x0ffloor_price_wei\x18\x05 \x01(\tR\rfloorPriceWei\x12(\n" +
	"\x10total_volume_wei\x18\x06 \x01(\tR\x0etotalVolumeWei\x12*\n" +
	"\x11average_price_wei\x18\a \x01(\tR\x0faveragePriceWei\x12$\n" +
	"\x0evolume_24h_wei\x18\b \x01(\tR\fvolume24hWei\x12\x1b\n" +
	"\tsales_24h\x18\t \x01(\x05R\bsales24h\x12<\n" +
	"\flast_sale_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSaleAt\x12<\n" +
	"\flast_mint_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastMintAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf9\x01\n" +
	"\x13CollectionAllowlist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x12&\n" +
	"\x0fmax_mint_amount\x18\x04 \x01(\x05R\rmaxMintAmount\x12'\n" +
	"\x10added_by_user_id\x18\x05 \x01(\tR\raddedByUserId\x125\n" +
	"\badded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\xc0\b\n" +
	"\x17CreateCollectionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x128\n" +
	"\x0etoken_standard\x18\x06 \x01(\x0e2\x11.pb.TokenStandardR\rtokenStandard\x12)\n" +
	"\x10deployer_address\x18\a \x01(\tR\x0fdeployerAddress\x12\x19\n" +
	"\bchain_id\x18\b \x01(\tR\achainId\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\n" +
	" \x01(\tR\tbannerUrl\x12,\n" +
	"\x12featured_image_url\x18\v \x01(\tR\x10featuredImageUrl\x12\x1f\n" +
	"\vwebsite_url\x18\f \x01(\tR\n" +
	"websiteUrl\x12&\n" +
	"\x0froyalty_fee_bps\x18\r \x01(\x05R\rroyaltyFeeBps\x12+\n" +
	"\x11royalty_recipient\x18\x0e \x01(\tR\x10royaltyRecipient\x12\x19\n" +
	"\bbase_uri\x18\x0f \x01(\tR\abaseUri\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x10 \x01(\x03R\tmaxSupply\x120\n" +
	"\x14mint_price_allowlist\x18\x11 \x01(\tR\x12mintPriceAllowlist\x12*\n" +
	"\x11mint_price_public\x18\x12 \x01(\tR\x0fmintPricePublic\x12B\n" +
	"\x0fmint_start_time\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\rmintStartTime\x12J\n" +
	"\x13allowlist_stage_end\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\x11allowlistStageEnd\x121\n" +
	"\x15mint_limit_per_wallet\x18\x15 \x01(\x05R\x12mintLimitPerWallet\x12!\n" +
	"\fmetadata_uri\x18\x16 \x01(\tR\vmetadataUri\x12\x1b\n" +
	"\tipfs_hash\x18\x17 \x01(\tR\bipfsHash\x12\x1f\n" +
	"\vdiscord_url\x18\x18 \x01(\tR\n" +
	"discordUrl\x12\x1f\n" +
	"\vtwitter_url\x18\x19 \x01(\tR\n" +
	"twitterUrl\x12#\n" +
	"\rinstagram_url\x18\x1a \x01(\tR\finstagramUrl\x12\x1d\n" +
	"\n" +
	"medium_url\x18\x1b \x01(\tR\tmediumUrl\x12!\n" +
	"\ftelegram_url\x18\x1c \x01(\tR\vtelegramUrl\"J\n" +
	"\x18CreateCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x0e.pb.CollectionR\n" +
	"collection\"\x80\x01\n" +
	"\x14GetCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\tR\achainId\"G\n" +
	"\x15GetCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x0e.pb.CollectionR\n" +
	"collection\"\x81\v\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x01R\bcategory\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"banner_url\x18\x06 \x01(\tH\x03R\tbannerUrl\x88\x01\x01\x121\n" +
	"\x12featured_image_url\x18\a \x01(\tH\x04R\x10featuredImageUrl\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\b \x01(\tH\x05R\n" +
	"websiteUrl\x88\x01\x01\x12$\n" +
	"\vdiscord_url\x18\t \x01(\tH\x06R\n" +
	"discordUrl\x88\x01\x01\x12$\n" +
	"\vtwitter_url\x18\n" +
	" \x01(\tH\aR\n" +
	"twitterUrl\x88\x01\x01\x12(\n" +
	"\rinstagram_url\x18\v \x01(\tH\bR\finstagramUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"medium_url\x18\f \x01(\tH\tR\tmediumUrl\x88\x01\x01\x12&\n" +
	"\ftelegram_url\x18\r \x01(\tH\n" +
	"R\vtelegramUrl\x88\x01\x01\x12.\n" +
	"\x10background_color\x18\x0e \x01(\tH\vR\x0fbackgroundColor\x88\x01\x01\x12\x1e\n" +
	"\bbase_uri\x18\x0f \x01(\tH\fR\abaseUri\x88\x01\x01\x125\n" +
	"\x14mint_price_allowlist\x18\x10 \x01(\tH\rR\x12mintPriceAllowlist\x88\x01\x01\x12/\n" +
	"\x11mint_price_public\x18\x11 \x01(\tH\x0eR\x0fmintPricePublic\x88\x01\x01\x12G\n" +
	"\x0fmint_start_time\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\x0fR\rmintStartTime\x88\x01\x01\x12O\n" +
	"\x13allowlist_stage_end\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampH\x10R\x11allowlistStageEnd\x88\x01\x01\x126\n" +
	"\x15mint_limit_per_wallet\x18\x14 \x01(\x05H\x11R\x12mintLimitPerWallet\x88\x01\x01\x121\n" +
	"\x06status\x18\x15 \x01(\x0e2\x14.pb.CollectionStatusH\x12R\x06status\x88\x01\x01\x12.\n" +
	"\x10contract_address\x18\x16 \x01(\tH\x13R\x0fcontractAddress\x88\x01\x01\x12*\n" +
	"\x0edeployed_block\x18\x17 \x01(\x03H\x14R\rdeployedBlock\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_categoryB\f\n" +
	"\n" +
	"_image_urlB\r\n" +
	"\v_banner_urlB\x15\n" +
	"\x13_featured_image_urlB\x0e\n" +
	"\f_website_urlB\x0e\n" +
	"\f_discord_urlB\x0e\n" +
	"\f_twitter_urlB\x10\n" +
	"\x0e_instagram_urlB\r\n" +
	"\v_medium_urlB\x0f\n" +
	"\r_telegram_urlB\x13\n" +
	"\x11_background_colorB\v\n" +
	"\t_base_uriB\x17\n" +
	"\x15_mint_price_allowlistB\x14\n" +
	"\x12_mint_price_publicB\x12\n" +
	"\x10_mint_start_timeB\x16\n" +
	"\x14_allowlist_stage_endB\x18\n" +
	"\x16_mint_limit_per_walletB\t\n" +
	"\a_statusB\x13\n" +
	"\x11_contract_addressB\x11\n" +
	"\x0f_deployed_block\"J\n" +
	"\x18UpdateCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x0e.pb.CollectionR\n" +
	"collection\"a\n" +
	"\x1cListCollectionsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8a\x02\n" +
	"\x16ListCollectionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\tR\achainId\x12$\n" +
	"\vis_verified\x18\a \x01(\bH\x00R\n" +
	"isVerified\x88\x01\x01\x12!\n" +
	"\fsearch_query\x18\b \x01(\tR\vsearchQueryB\x0e\n" +
	"\f_is_verified\"\x96\x01\n" +
	"\x17ListCollectionsResponse\x120\n" +
	"\vcollections\x18\x01 \x03(\v2\x0e.pb.CollectionR\vcollections\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xa8\x01\n" +
	"\x15AddToAllowlistRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10wallet_addresses\x18\x03 \x03(\tR\x0fwalletAddresses\x12&\n" +
	"\x0fmax_mint_amount\x18\x04 \x01(\x05R\rmaxMintAmount\"9\n" +
	"\x16AddToAllowlistResponse\x12\x1f\n" +
	"\vadded_count\x18\x01 \x01(\x05R\n" +
	"addedCount\"B\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x18DeleteCollectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x01\n" +
	"\x1cProcessIndexerWebhookRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x03R\achainId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tdata_json\x18\x04 \x01(\tR\bdataJson\"S\n" +
	"\x1dProcessIndexerWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*f\n" +
	"\rTokenStandard\x12\x1e\n" +
	"\x1aTOKEN_STANDARD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TOKEN_STANDARD_ERC721\x10\x01\x12\x1a\n" +
	"\x16TOKEN_STANDARD_ERC1155\x10\x02*\xb2\x01\n" +
	"\x10CollectionStatus\x12!\n" +
	"\x1dCOLLECTION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COLLECTION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aCOLLECTION_STATUS_DEPLOYED\x10\x02\x12\x1c\n" +
	"\x18COLLECTION_STATUS_FAILED\x10\x03\x12\x1e\n" +
	"\x1aCOLLECTION_STATUS_ARCHIVED\x10\x04*\x95\x01\n" +
	"\vIndexStatus\x12\x1c\n" +
	"\x18INDEX_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INDEX_STATUS_NOT_STARTED\x10\x01\x12\x18\n" +
	"\x14INDEX_STATUS_SYNCING\x10\x02\x12\x17\n" +
	"\x13INDEX_STATUS_SYNCED\x10\x03\x12\x17\n" +
	"\x13INDEX_STATUS_FAILED\x10\x042\x91\x05\n" +
	"\x11CollectionService\x12M\n" +
	"\x10CreateCollection\x12\x1b.pb.CreateCollectionRequest\x1a\x1c.pb.CreateCollectionResponse\x12D\n" +
	"\rGetCollection\x12\x18.pb.GetCollectionRequest\x1a\x19.pb.GetCollectionResponse\x12M\n" +
	"\x10UpdateCollection\x12\x1b.pb.UpdateCollectionRequest\x1a\x1c.pb.UpdateCollectionResponse\x12V\n" +
	"\x15ListCollectionsByUser\x12 .pb.ListCollectionsByUserRequest\x1a\x1b.pb.ListCollectionsResponse\x12J\n" +
	"\x0fListCollections\x12\x1a.pb.ListCollectionsRequest\x1a\x1b.pb.ListCollectionsResponse\x12G\n" +
	"\x0eAddToAllowlist\x12\x19.pb.AddToAllowlistRequest\x1a\x1a.pb.AddToAllowlistResponse\x12M\n" +
	"\x10DeleteCollection\x12\x1b.pb.DeleteCollectionRequest\x1a\x1c.pb.DeleteCollectionResponse\x12\\\n" +
	"\x15ProcessIndexerWebhook\x12 .pb.ProcessIndexerWebhookRequest\x1a!.pb.ProcessIndexerWebhookResponseB8Z6github.com/quangdang46/NFT-Marketplace/shared/proto/pbb\x06proto3"

var (
	file_proto_collection_proto_rawDescOnce sync.Once
	file_proto_collection_proto_rawDescData []byte
)

func file_proto_collection_proto_rawDescGZIP() []byte {
	file_proto_collection_proto_rawDescOnce.Do(func() {
		file_proto_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collection_proto_rawDesc), len(file_proto_collection_proto_rawDesc)))
	})
	return file_proto_collection_proto_rawDescData
}

var file_proto_collection_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_collection_proto_goTypes = []any{
	(TokenStandard)(0),                    // 0: pb.TokenStandard
	(CollectionStatus)(0),                 // 1: pb.CollectionStatus
	(IndexStatus)(0),                      // 2: pb.IndexStatus
	(*Collection)(nil),                    // 3: pb.Collection
	(*CollectionMetadata)(nil),            // 4: pb.CollectionMetadata
	(*CollectionStats)(nil),               // 5: pb.CollectionStats
	(*CollectionAllowlist)(nil),           // 6: pb.CollectionAllowlist
	(*CreateCollectionRequest)(nil),       // 7: pb.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),      // 8: pb.CreateCollectionResponse
	(*GetCollectionRequest)(nil),          // 9: pb.GetCollectionRequest
	(*GetCollectionResponse)(nil),         // 10: pb.GetCollectionResponse
	(*UpdateCollectionRequest)(nil),       // 11: pb.UpdateCollectionRequest
	(*UpdateCollectionResponse)(nil),      // 12: pb.UpdateCollectionResponse
	(*ListCollectionsByUserRequest)(nil),  // 13: pb.ListCollectionsByUserRequest
	(*ListCollectionsRequest)(nil),        // 14: pb.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),       // 15: pb.ListCollectionsResponse
	(*AddToAllowlistRequest)(nil),         // 16: pb.AddToAllowlistRequest
	(*AddToAllowlistResponse)(nil),        // 17: pb.AddToAllowlistResponse
	(*DeleteCollectionRequest)(nil),       // 18: pb.DeleteCollectionRequest
	(*DeleteCollectionResponse)(nil),      // 19: pb.DeleteCollectionResponse
	(*ProcessIndexerWebhookRequest)(nil),  // 20: pb.ProcessIndexerWebhookRequest
	(*ProcessIndexerWebhookResponse)(nil), // 21: pb.ProcessIndexerWebhookResponse
	(*timestamppb.Timestamp)(nil),         // 22: google.protobuf.Timestamp
}
var file_proto_collection_proto_depIdxs = []int32{
	0,  // 0: pb.Collection.token_standard:type_name -> pb.TokenStandard
	1,  // 1: pb.Collection.status:type_name -> pb.CollectionStatus
	22, // 2: pb.Collection.deployed_at:type_name -> google.protobuf.Timestamp
	2,  // 3: pb.Collection.index_status:type_name -> pb.IndexStatus
	22, // 4: pb.Collection.mint_start_time:type_name -> google.protobuf.Timestamp
	22, // 5: pb.Collection.allowlist_stage_end:type_name -> google.protobuf.Timestamp
	22, // 6: pb.Collection.created_at:type_name -> google.protobuf.Timestamp
	22, // 7: pb.Collection.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 8: pb.Collection.metadata:type_name -> pb.CollectionMetadata
	5,  // 9: pb.Collection.stats:type_name -> pb.CollectionStats
	22, // 10: pb.CollectionStats.last_sale_at:type_name -> google.protobuf.Timestamp
	22, // 11: pb.CollectionStats.last_mint_at:type_name -> google.protobuf.Timestamp
	22, // 12: pb.CollectionStats.updated_at:type_name -> google.protobuf.Timestamp
	22, // 13: pb.CollectionAllowlist.added_at:type_name -> google.protobuf.Timestamp
	0,  // 14: pb.CreateCollectionRequest.token_standard:type_name -> pb.TokenStandard
	22, // 15: pb.CreateCollectionRequest.mint_start_time:type_name -> google.protobuf.Timestamp
	22, // 16: pb.CreateCollectionRequest.allowlist_stage_end:type_name -> google.protobuf.Timestamp
	3,  // 17: pb.CreateCollectionResponse.collection:type_name -> pb.Collection
	3,  // 18: pb.GetCollectionResponse.collection:type_name -> pb.Collection
	22, // 19: pb.UpdateCollectionRequest.mint_start_time:type_name -> google.protobuf.Timestamp
	22, // 20: pb.UpdateCollectionRequest.allowlist_stage_end:type_name -> google.protobuf.Timestamp
	1,  // 21: pb.UpdateCollectionRequest.status:type_name -> pb.CollectionStatus
	3,  // 22: pb.UpdateCollectionResponse.collection:type_name -> pb.Collection
	3,  // 23: pb.ListCollectionsResponse.collections:type_name -> pb.Collection
	7,  // 24: pb.CollectionService.CreateCollection:input_type -> pb.CreateCollectionRequest
	9,  // 25: pb.CollectionService.GetCollection:input_type -> pb.GetCollectionRequest
	11, // 26: pb.CollectionService.UpdateCollection:input_type -> pb.UpdateCollectionRequest
	13, // 27: pb.CollectionService.ListCollectionsByUser:input_type -> pb.ListCollectionsByUserRequest
	14, // 28: pb.CollectionService.ListCollections:input_type -> pb.ListCollectionsRequest
	16, // 29: pb.CollectionService.AddToAllowlist:input_type -> pb.AddToAllowlistRequest
	18, // 30: pb.CollectionService.DeleteCollection:input_type -> pb.DeleteCollectionRequest
	20, // 31: pb.CollectionService.ProcessIndexerWebhook:input_type -> pb.ProcessIndexerWebhookRequest
	8,  // 32: pb.CollectionService.CreateCollection:output_type -> pb.CreateCollectionResponse
	10, // 33: pb.CollectionService.GetCollection:output_type -> pb.GetCollectionResponse
	12, // 34: pb.CollectionService.UpdateCollection:output_type -> pb.UpdateCollectionResponse
	15, // 35: pb.CollectionService.ListCollectionsByUser:output_type -> pb.ListCollectionsResponse
	15, // 36: pb.CollectionService.ListCollections:output_type -> pb.ListCollectionsResponse
	17, // 37: pb.CollectionService.AddToAllowlist:output_type -> pb.AddToAllowlistResponse
	19, // 38: pb.CollectionService.DeleteCollection:output_type -> pb.DeleteCollectionResponse
	21, // 39: pb.CollectionService.ProcessIndexerWebhook:output_type -> pb.ProcessIndexerWebhookResponse
	32, // [32:40] is the sub-list for method output_type
	24, // [24:32] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_collection_proto_init() }
func file_proto_collection_proto_init() {
	if File_proto_collection_proto != nil {
		return
	}
	file_proto_collection_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_collection_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collection_proto_rawDesc), len(file_proto_collection_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collection_proto_goTypes,
		DependencyIndexes: file_proto_collection_proto_depIdxs,
		EnumInfos:         file_proto_collection_proto_enumTypes,
		MessageInfos:      file_proto_collection_proto_msgTypes,
	}.Build()
	File_proto_collection_proto = out.File
	file_proto_collection_proto_goTypes = nil
	file_proto_collection_proto_depIdxs = nil
}
