// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0--rc1
// source: proto/media.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadMediaRequest for single file upload
type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Folder        string                 `protobuf:"bytes,5,opt,name=folder,proto3" json:"folder,omitempty"` // optional: collections, nfts, avatars
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`     // optional: for categorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadMediaRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMediaRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadMediaRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *UploadMediaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// UploadMediaResponse
type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// BatchUploadMediaRequest for multiple files
type BatchUploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Files         []*FileData            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Folder        string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUploadMediaRequest) Reset() {
	*x = BatchUploadMediaRequest{}
	mi := &file_proto_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadMediaRequest) ProtoMessage() {}

func (x *BatchUploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUploadMediaRequest.ProtoReflect.Descriptor instead.
func (*BatchUploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{2}
}

func (x *BatchUploadMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchUploadMediaRequest) GetFiles() []*FileData {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BatchUploadMediaRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

// FileData represents a single file in batch upload
type FileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_proto_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{3}
}

func (x *FileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// BatchUploadMediaResponse
type BatchUploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*MediaInfo           `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUploadMediaResponse) Reset() {
	*x = BatchUploadMediaResponse{}
	mi := &file_proto_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUploadMediaResponse) ProtoMessage() {}

func (x *BatchUploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUploadMediaResponse.ProtoReflect.Descriptor instead.
func (*BatchUploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUploadMediaResponse) GetMedia() []*MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// GetMediaRequest
type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_proto_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

// GetMediaResponse
type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_proto_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// MediaInfo represents uploaded media information
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	MediaType     string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // image, video, audio
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`                              // ImageKit URL
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Width         int32                  `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	IpfsHash      string                 `protobuf:"bytes,10,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`  // empty initially, set after async pinning
	IpfsUrl       string                 `protobuf:"bytes,11,opt,name=ipfs_url,json=ipfsUrl,proto3" json:"ipfs_url,omitempty"`     // empty initially
	IsPinned      bool                   `protobuf:"varint,12,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"` // false initially, true after ~10-30s
	PinnedAt      string                 `protobuf:"bytes,13,opt,name=pinned_at,json=pinnedAt,proto3" json:"pinned_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_proto_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_proto_media_proto_rawDescGZIP(), []int{7}
}

func (x *MediaInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MediaInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaInfo) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MediaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaInfo) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaInfo) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *MediaInfo) GetIpfsUrl() string {
	if x != nil {
		return x.IpfsUrl
	}
	return ""
}

func (x *MediaInfo) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *MediaInfo) GetPinnedAt() string {
	if x != nil {
		return x.PinnedAt
	}
	return ""
}

func (x *MediaInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_media_proto protoreflect.FileDescriptor

const file_proto_media_proto_rawDesc = "" +
	"\n" +
	"\x11proto/media.proto\x12\x05media\"\xb5\x01\n" +
	"\x12UploadMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06folder\x18\x05 \x01(\tR\x06folder\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"=\n" +
	"\x13UploadMediaResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"q\n" +
	"\x17BatchUploadMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x05files\x18\x02 \x03(\v2\x0f.media.FileDataR\x05files\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\"]\n" +
	"\bFileData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"B\n" +
	"\x18BatchUploadMediaResponse\x12&\n" +
	"\x05media\x18\x01 \x03(\v2\x10.media.MediaInfoR\x05media\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\":\n" +
	"\x10GetMediaResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"\x87\x03\n" +
	"\tMediaInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x12\x14\n" +
	"\x05width\x18\b \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\t \x01(\x05R\x06height\x12\x1b\n" +
	"\tipfs_hash\x18\n" +
	" \x01(\tR\bipfsHash\x12\x19\n" +
	"\bipfs_url\x18\v \x01(\tR\aipfsUrl\x12\x1b\n" +
	"\tis_pinned\x18\f \x01(\bR\bisPinned\x12\x1b\n" +
	"\tpinned_at\x18\r \x01(\tR\bpinnedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt2\xe6\x01\n" +
	"\fMediaService\x12D\n" +
	"\vUploadMedia\x12\x19.media.UploadMediaRequest\x1a\x1a.media.UploadMediaResponse\x12S\n" +
	"\x10BatchUploadMedia\x12\x1e.media.BatchUploadMediaRequest\x1a\x1f.media.BatchUploadMediaResponse\x12;\n" +
	"\bGetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponseB9Z7github.com/zunokit/zuno-marketplace-api/shared/proto/pbb\x06proto3"

var (
	file_proto_media_proto_rawDescOnce sync.Once
	file_proto_media_proto_rawDescData []byte
)

func file_proto_media_proto_rawDescGZIP() []byte {
	file_proto_media_proto_rawDescOnce.Do(func() {
		file_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)))
	})
	return file_proto_media_proto_rawDescData
}

var file_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_media_proto_goTypes = []any{
	(*UploadMediaRequest)(nil),       // 0: media.UploadMediaRequest
	(*UploadMediaResponse)(nil),      // 1: media.UploadMediaResponse
	(*BatchUploadMediaRequest)(nil),  // 2: media.BatchUploadMediaRequest
	(*FileData)(nil),                 // 3: media.FileData
	(*BatchUploadMediaResponse)(nil), // 4: media.BatchUploadMediaResponse
	(*GetMediaRequest)(nil),          // 5: media.GetMediaRequest
	(*GetMediaResponse)(nil),         // 6: media.GetMediaResponse
	(*MediaInfo)(nil),                // 7: media.MediaInfo
}
var file_proto_media_proto_depIdxs = []int32{
	7, // 0: media.UploadMediaResponse.media:type_name -> media.MediaInfo
	3, // 1: media.BatchUploadMediaRequest.files:type_name -> media.FileData
	7, // 2: media.BatchUploadMediaResponse.media:type_name -> media.MediaInfo
	7, // 3: media.GetMediaResponse.media:type_name -> media.MediaInfo
	0, // 4: media.MediaService.UploadMedia:input_type -> media.UploadMediaRequest
	2, // 5: media.MediaService.BatchUploadMedia:input_type -> media.BatchUploadMediaRequest
	5, // 6: media.MediaService.GetMedia:input_type -> media.GetMediaRequest
	1, // 7: media.MediaService.UploadMedia:output_type -> media.UploadMediaResponse
	4, // 8: media.MediaService.BatchUploadMedia:output_type -> media.BatchUploadMediaResponse
	6, // 9: media.MediaService.GetMedia:output_type -> media.GetMediaResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_media_proto_init() }
func file_proto_media_proto_init() {
	if File_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_proto_rawDesc), len(file_proto_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_proto_goTypes,
		DependencyIndexes: file_proto_media_proto_depIdxs,
		MessageInfos:      file_proto_media_proto_msgTypes,
	}.Build()
	File_proto_media_proto = out.File
	file_proto_media_proto_goTypes = nil
	file_proto_media_proto_depIdxs = nil
}
