package service

import (
	"testing"
)

// Note: SIWE message parsing tests are skipped for now as they require exact
// EIP-4361 message format which will be generated by the frontend client.
// The SIWE library itself is well-tested. We'll add integration tests once
// we have real messages from the frontend.

func TestSIWEService_New(t *testing.T) {
	service := NewSIWEService()
	if service == nil {
		t.Fatal("Expected NewSIWEService to return non-nil service")
	}
}

// TODO: Add integration tests with real SIWE messages from frontend
// These tests should be added when integrating with the frontend RainbowKit flow
