// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc1
// source: media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaKind int32

const (
	MediaKind_MEDIA_KIND_UNSPECIFIED MediaKind = 0
	MediaKind_IMAGE                  MediaKind = 1
	MediaKind_VIDEO                  MediaKind = 2
	MediaKind_AUDIO                  MediaKind = 3
	MediaKind_OTHER                  MediaKind = 9
)

// Enum value maps for MediaKind.
var (
	MediaKind_name = map[int32]string{
		0: "MEDIA_KIND_UNSPECIFIED",
		1: "IMAGE",
		2: "VIDEO",
		3: "AUDIO",
		9: "OTHER",
	}
	MediaKind_value = map[string]int32{
		"MEDIA_KIND_UNSPECIFIED": 0,
		"IMAGE":                  1,
		"VIDEO":                  2,
		"AUDIO":                  3,
		"OTHER":                  9,
	}
)

func (x MediaKind) Enum() *MediaKind {
	p := new(MediaKind)
	*p = x
	return p
}

func (x MediaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (MediaKind) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x MediaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaKind.Descriptor instead.
func (MediaKind) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

type VariantFormat int32

const (
	VariantFormat_VARIANT_FORMAT_UNSPECIFIED VariantFormat = 0
	VariantFormat_JPG                        VariantFormat = 1
	VariantFormat_WEBP                       VariantFormat = 2
	VariantFormat_PNG                        VariantFormat = 3
	VariantFormat_MP4                        VariantFormat = 10
	VariantFormat_GIF                        VariantFormat = 11
)

// Enum value maps for VariantFormat.
var (
	VariantFormat_name = map[int32]string{
		0:  "VARIANT_FORMAT_UNSPECIFIED",
		1:  "JPG",
		2:  "WEBP",
		3:  "PNG",
		10: "MP4",
		11: "GIF",
	}
	VariantFormat_value = map[string]int32{
		"VARIANT_FORMAT_UNSPECIFIED": 0,
		"JPG":                        1,
		"WEBP":                       2,
		"PNG":                        3,
		"MP4":                        10,
		"GIF":                        11,
	}
)

func (x VariantFormat) Enum() *VariantFormat {
	p := new(VariantFormat)
	*p = x
	return p
}

func (x VariantFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariantFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[1].Descriptor()
}

func (VariantFormat) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[1]
}

func (x VariantFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariantFormat.Descriptor instead.
func (VariantFormat) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

type PinStatus int32

const (
	PinStatus_PIN_STATUS_UNSPECIFIED PinStatus = 0
	PinStatus_PENDING                PinStatus = 1
	PinStatus_PINNING                PinStatus = 2
	PinStatus_PINNED                 PinStatus = 3
	PinStatus_FAILED                 PinStatus = 4
)

// Enum value maps for PinStatus.
var (
	PinStatus_name = map[int32]string{
		0: "PIN_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "PINNING",
		3: "PINNED",
		4: "FAILED",
	}
	PinStatus_value = map[string]int32{
		"PIN_STATUS_UNSPECIFIED": 0,
		"PENDING":                1,
		"PINNING":                2,
		"PINNED":                 3,
		"FAILED":                 4,
	}
)

func (x PinStatus) Enum() *PinStatus {
	p := new(PinStatus)
	*p = x
	return p
}

func (x PinStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PinStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[2].Descriptor()
}

func (PinStatus) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[2]
}

func (x PinStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PinStatus.Descriptor instead.
func (PinStatus) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

type MediaVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CdnUrl        string                 `protobuf:"bytes,2,opt,name=cdn_url,json=cdnUrl,proto3" json:"cdn_url,omitempty"`
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Format        VariantFormat          `protobuf:"varint,5,opt,name=format,proto3,enum=media.VariantFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaVariant) Reset() {
	*x = MediaVariant{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaVariant) ProtoMessage() {}

func (x *MediaVariant) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaVariant.ProtoReflect.Descriptor instead.
func (*MediaVariant) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaVariant) GetCdnUrl() string {
	if x != nil {
		return x.CdnUrl
	}
	return ""
}

func (x *MediaVariant) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaVariant) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaVariant) GetFormat() VariantFormat {
	if x != nil {
		return x.Format
	}
	return VariantFormat_VARIANT_FORMAT_UNSPECIFIED
}

type Asset struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          MediaKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=media.MediaKind" json:"kind,omitempty"`
	Mime          string                  `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Bytes         uint64                  `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Width         *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=height,proto3" json:"height,omitempty"`
	S3Key         string                  `protobuf:"bytes,7,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	IpfsCid       *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=ipfs_cid,json=ipfsCid,proto3" json:"ipfs_cid,omitempty"`                             // set nếu đã PINNED
	PinStatus     PinStatus               `protobuf:"varint,9,opt,name=pin_status,json=pinStatus,proto3,enum=media.PinStatus" json:"pin_status,omitempty"` // PENDING|PINNING|PINNED|FAILED
	Sha256        string                  `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RefCount      uint32                  `protobuf:"varint,12,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	Variants      []*MediaVariant         `protobuf:"bytes,13,rep,name=variants,proto3" json:"variants,omitempty"`
	GatewayUrl    *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"` // https://gateway.pinata.cloud/ipfs/<cid>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetKind() MediaKind {
	if x != nil {
		return x.Kind
	}
	return MediaKind_MEDIA_KIND_UNSPECIFIED
}

func (x *Asset) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Asset) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Asset) GetWidth() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *Asset) GetHeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *Asset) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Asset) GetIpfsCid() *wrapperspb.StringValue {
	if x != nil {
		return x.IpfsCid
	}
	return nil
}

func (x *Asset) GetPinStatus() PinStatus {
	if x != nil {
		return x.PinStatus
	}
	return PinStatus_PIN_STATUS_UNSPECIFIED
}

func (x *Asset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetRefCount() uint32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *Asset) GetVariants() []*MediaVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Asset) GetGatewayUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.GatewayUrl
	}
	return nil
}

type SingleUploadRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	FileData      []byte                  `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                  `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mime          string                  `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Kind          MediaKind               `protobuf:"varint,4,opt,name=kind,proto3,enum=media.MediaKind" json:"kind,omitempty"`
	Width         *wrapperspb.UInt32Value `protobuf:"bytes,5,opt,name=width,proto3" json:"width,omitempty"`                    // optional
	Height        *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=height,proto3" json:"height,omitempty"`                  // optional
	OwnerId       string                  `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // optional (audit/link)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleUploadRequest) Reset() {
	*x = SingleUploadRequest{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleUploadRequest) ProtoMessage() {}

func (x *SingleUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleUploadRequest.ProtoReflect.Descriptor instead.
func (*SingleUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *SingleUploadRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *SingleUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SingleUploadRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *SingleUploadRequest) GetKind() MediaKind {
	if x != nil {
		return x.Kind
	}
	return MediaKind_MEDIA_KIND_UNSPECIFIED
}

func (x *SingleUploadRequest) GetWidth() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *SingleUploadRequest) GetHeight() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Height
	}
	return nil
}

func (x *SingleUploadRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UploadAndPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"` // asset.ipfs_cid MUST be set, pin_status=PINNED
	Deduplicated  bool                   `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAndPinResponse) Reset() {
	*x = UploadAndPinResponse{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAndPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAndPinResponse) ProtoMessage() {}

func (x *UploadAndPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAndPinResponse.ProtoReflect.Descriptor instead.
func (*UploadAndPinResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *UploadAndPinResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *UploadAndPinResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssetByCidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetByCidRequest) Reset() {
	*x = GetAssetByCidRequest{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetByCidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetByCidRequest) ProtoMessage() {}

func (x *GetAssetByCidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetByCidRequest.ProtoReflect.Descriptor instead.
func (*GetAssetByCidRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetByCidRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type GetAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x93\x01\n" +
	"\fMediaVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acdn_url\x18\x02 \x01(\tR\x06cdnUrl\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x12,\n" +
	"\x06format\x18\x05 \x01(\x0e2\x14.media.VariantFormatR\x06format\"\xb2\x04\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.media.MediaKindR\x04kind\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x04R\x05bytes\x122\n" +
	"\x05width\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05width\x124\n" +
	"\x06height\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06height\x12\x15\n" +
	"\x06s3_key\x18\a \x01(\tR\x05s3Key\x127\n" +
	"\bipfs_cid\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\aipfsCid\x12/\n" +
	"\n" +
	"pin_status\x18\t \x01(\x0e2\x10.media.PinStatusR\tpinStatus\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\tR\x06sha256\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tref_count\x18\f \x01(\rR\brefCount\x12/\n" +
	"\bvariants\x18\r \x03(\v2\x13.media.MediaVariantR\bvariants\x12=\n" +
	"\vgateway_url\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"gatewayUrl\"\x8d\x02\n" +
	"\x13SingleUploadRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\x12$\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x10.media.MediaKindR\x04kind\x122\n" +
	"\x05width\x18\x05 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x05width\x124\n" +
	"\x06height\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06height\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\"^\n" +
	"\x14UploadAndPinResponse\x12\"\n" +
	"\x05asset\x18\x01 \x01(\v2\f.media.AssetR\x05asset\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"!\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x14GetAssetByCidRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"6\n" +
	"\x10GetAssetResponse\x12\"\n" +
	"\x05asset\x18\x01 \x01(\v2\f.media.AssetR\x05asset*S\n" +
	"\tMediaKind\x12\x1a\n" +
	"\x16MEDIA_KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03\x12\t\n" +
	"\x05OTHER\x10\t*]\n" +
	"\rVariantFormat\x12\x1e\n" +
	"\x1aVARIANT_FORMAT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03JPG\x10\x01\x12\b\n" +
	"\x04WEBP\x10\x02\x12\a\n" +
	"\x03PNG\x10\x03\x12\a\n" +
	"\x03MP4\x10\n" +
	"\x12\a\n" +
	"\x03GIF\x10\v*Y\n" +
	"\tPinStatus\x12\x1a\n" +
	"\x16PIN_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aPINNING\x10\x02\x12\n" +
	"\n" +
	"\x06PINNED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042\xdf\x01\n" +
	"\fMediaService\x12K\n" +
	"\x10UploadSingleFile\x12\x1a.media.SingleUploadRequest\x1a\x1b.media.UploadAndPinResponse\x12;\n" +
	"\bGetAsset\x12\x16.media.GetAssetRequest\x1a\x17.media.GetAssetResponse\x12E\n" +
	"\rGetAssetByCid\x12\x1b.media.GetAssetByCidRequest\x1a\x17.media.GetAssetResponseB\x1aZ\x18shared/proto/media;mediab\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_media_proto_goTypes = []any{
	(MediaKind)(0),                 // 0: media.MediaKind
	(VariantFormat)(0),             // 1: media.VariantFormat
	(PinStatus)(0),                 // 2: media.PinStatus
	(*MediaVariant)(nil),           // 3: media.MediaVariant
	(*Asset)(nil),                  // 4: media.Asset
	(*SingleUploadRequest)(nil),    // 5: media.SingleUploadRequest
	(*UploadAndPinResponse)(nil),   // 6: media.UploadAndPinResponse
	(*GetAssetRequest)(nil),        // 7: media.GetAssetRequest
	(*GetAssetByCidRequest)(nil),   // 8: media.GetAssetByCidRequest
	(*GetAssetResponse)(nil),       // 9: media.GetAssetResponse
	(*wrapperspb.UInt32Value)(nil), // 10: google.protobuf.UInt32Value
	(*wrapperspb.StringValue)(nil), // 11: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_media_proto_depIdxs = []int32{
	1,  // 0: media.MediaVariant.format:type_name -> media.VariantFormat
	0,  // 1: media.Asset.kind:type_name -> media.MediaKind
	10, // 2: media.Asset.width:type_name -> google.protobuf.UInt32Value
	10, // 3: media.Asset.height:type_name -> google.protobuf.UInt32Value
	11, // 4: media.Asset.ipfs_cid:type_name -> google.protobuf.StringValue
	2,  // 5: media.Asset.pin_status:type_name -> media.PinStatus
	12, // 6: media.Asset.created_at:type_name -> google.protobuf.Timestamp
	3,  // 7: media.Asset.variants:type_name -> media.MediaVariant
	11, // 8: media.Asset.gateway_url:type_name -> google.protobuf.StringValue
	0,  // 9: media.SingleUploadRequest.kind:type_name -> media.MediaKind
	10, // 10: media.SingleUploadRequest.width:type_name -> google.protobuf.UInt32Value
	10, // 11: media.SingleUploadRequest.height:type_name -> google.protobuf.UInt32Value
	4,  // 12: media.UploadAndPinResponse.asset:type_name -> media.Asset
	4,  // 13: media.GetAssetResponse.asset:type_name -> media.Asset
	5,  // 14: media.MediaService.UploadSingleFile:input_type -> media.SingleUploadRequest
	7,  // 15: media.MediaService.GetAsset:input_type -> media.GetAssetRequest
	8,  // 16: media.MediaService.GetAssetByCid:input_type -> media.GetAssetByCidRequest
	6,  // 17: media.MediaService.UploadSingleFile:output_type -> media.UploadAndPinResponse
	9,  // 18: media.MediaService.GetAsset:output_type -> media.GetAssetResponse
	9,  // 19: media.MediaService.GetAssetByCid:output_type -> media.GetAssetResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
