name: Fast CI

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: ['develop']

# Cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '1.25.1'

jobs:
  # Quick validation without all services
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For changed files detection

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.go
            go.mod
            go.sum

      - name: Download dependencies
        run: go mod download

      # Only test changed packages
      - name: Test changed packages
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          CHANGED_DIRS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs -n1 dirname | sort -u | grep -E '^services/' | cut -d'/' -f1-2 | sort -u)

          if [ -z "$CHANGED_DIRS" ]; then
            echo "No service changes detected, running all tests"
            go test -race -timeout=5m ./...
          else
            echo "Testing changed services: $CHANGED_DIRS"
            for dir in $CHANGED_DIRS; do
              if [ -d "$dir" ]; then
                echo "Testing $dir"
                go test -race -timeout=5m ./$dir/...
              fi
            done
          fi

      # Quick build check
      - name: Build check
        run: |
          go build -o /dev/null ./...

  # Fast lint
  quick-lint:
    name: Quick Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --fast --timeout=5m
          skip-cache: false
